/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.kinstalk.voip.sdk;

public enum EngineSdkCPUManufacturer {
  ES_CPU_MANUFACTURER_UNKNOWN,
  ES_CPU_MANUFACTURER_MTK,
  ES_CPU_MANUFACTURER_QCOM,
  ES_CPU_MANUFACTURER_INTEL;

  public final int swigValue() {
    return swigValue;
  }

  public static EngineSdkCPUManufacturer swigToEnum(int swigValue) {
    EngineSdkCPUManufacturer[] swigValues = EngineSdkCPUManufacturer.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (EngineSdkCPUManufacturer swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + EngineSdkCPUManufacturer.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private EngineSdkCPUManufacturer() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private EngineSdkCPUManufacturer(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private EngineSdkCPUManufacturer(EngineSdkCPUManufacturer swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

