/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.kinstalk.voip.sdk;

public class EngineSdkCallResultReport {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected EngineSdkCallResultReport(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(EngineSdkCallResultReport obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        EngineSdkJNI.delete_EngineSdkCallResultReport(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public EngineSdkCallResultReport() {
    this(EngineSdkJNI.new_EngineSdkCallResultReport(), true);
  }

  public void setBiRemoteVideoAvgFps(float value) {
    EngineSdkJNI.EngineSdkCallResultReport_biRemoteVideoAvgFps_set(swigCPtr, this, value);
  }

  public float getBiRemoteVideoAvgFps() {
    return EngineSdkJNI.EngineSdkCallResultReport_biRemoteVideoAvgFps_get(swigCPtr, this);
  }

  public void setBiRemoteVideoLowerFpsTimes(int value) {
    EngineSdkJNI.EngineSdkCallResultReport_biRemoteVideoLowerFpsTimes_set(swigCPtr, this, value);
  }

  public int getBiRemoteVideoLowerFpsTimes() {
    return EngineSdkJNI.EngineSdkCallResultReport_biRemoteVideoLowerFpsTimes_get(swigCPtr, this);
  }

  public void setBiVideoResolutionComposition(String value) {
    EngineSdkJNI.EngineSdkCallResultReport_biVideoResolutionComposition_set(swigCPtr, this, value);
  }

  public String getBiVideoResolutionComposition() {
    return EngineSdkJNI.EngineSdkCallResultReport_biVideoResolutionComposition_get(swigCPtr, this);
  }

  public void setBiVideoSampleInfo(EngineSdkVideoBiInfo value) {
    EngineSdkJNI.EngineSdkCallResultReport_biVideoSampleInfo_set(swigCPtr, this, EngineSdkVideoBiInfo.getCPtr(value), value);
  }

  public EngineSdkVideoBiInfo getBiVideoSampleInfo() {
    long cPtr = EngineSdkJNI.EngineSdkCallResultReport_biVideoSampleInfo_get(swigCPtr, this);
    return (cPtr == 0) ? null : new EngineSdkVideoBiInfo(cPtr, false);
  }

  public void setBiAudioSampleInfo(EngineSdkAudioBiInfo value) {
    EngineSdkJNI.EngineSdkCallResultReport_biAudioSampleInfo_set(swigCPtr, this, EngineSdkAudioBiInfo.getCPtr(value), value);
  }

  public EngineSdkAudioBiInfo getBiAudioSampleInfo() {
    long cPtr = EngineSdkJNI.EngineSdkCallResultReport_biAudioSampleInfo_get(swigCPtr, this);
    return (cPtr == 0) ? null : new EngineSdkAudioBiInfo(cPtr, false);
  }

  public void setBiVideoLandscapeTimeInMs(int value) {
    EngineSdkJNI.EngineSdkCallResultReport_biVideoLandscapeTimeInMs_set(swigCPtr, this, value);
  }

  public int getBiVideoLandscapeTimeInMs() {
    return EngineSdkJNI.EngineSdkCallResultReport_biVideoLandscapeTimeInMs_get(swigCPtr, this);
  }

  public void setBiVideoPortaitTimeInMs(int value) {
    EngineSdkJNI.EngineSdkCallResultReport_biVideoPortaitTimeInMs_set(swigCPtr, this, value);
  }

  public int getBiVideoPortaitTimeInMs() {
    return EngineSdkJNI.EngineSdkCallResultReport_biVideoPortaitTimeInMs_get(swigCPtr, this);
  }

  public void setBiAudioOutputLoudSpeakerTimeInMs(int value) {
    EngineSdkJNI.EngineSdkCallResultReport_biAudioOutputLoudSpeakerTimeInMs_set(swigCPtr, this, value);
  }

  public int getBiAudioOutputLoudSpeakerTimeInMs() {
    return EngineSdkJNI.EngineSdkCallResultReport_biAudioOutputLoudSpeakerTimeInMs_get(swigCPtr, this);
  }

  public void setBiAudioOutputEarphoneTimeInMs(int value) {
    EngineSdkJNI.EngineSdkCallResultReport_biAudioOutputEarphoneTimeInMs_set(swigCPtr, this, value);
  }

  public int getBiAudioOutputEarphoneTimeInMs() {
    return EngineSdkJNI.EngineSdkCallResultReport_biAudioOutputEarphoneTimeInMs_get(swigCPtr, this);
  }

  public void setBiAudioOutputSmallerSpeakerTimeInMs(int value) {
    EngineSdkJNI.EngineSdkCallResultReport_biAudioOutputSmallerSpeakerTimeInMs_set(swigCPtr, this, value);
  }

  public int getBiAudioOutputSmallerSpeakerTimeInMs() {
    return EngineSdkJNI.EngineSdkCallResultReport_biAudioOutputSmallerSpeakerTimeInMs_get(swigCPtr, this);
  }

  public void setBiCameraOnTimeInMs(int value) {
    EngineSdkJNI.EngineSdkCallResultReport_biCameraOnTimeInMs_set(swigCPtr, this, value);
  }

  public int getBiCameraOnTimeInMs() {
    return EngineSdkJNI.EngineSdkCallResultReport_biCameraOnTimeInMs_get(swigCPtr, this);
  }

  public void setBiCameraOffTimeInMs(int value) {
    EngineSdkJNI.EngineSdkCallResultReport_biCameraOffTimeInMs_set(swigCPtr, this, value);
  }

  public int getBiCameraOffTimeInMs() {
    return EngineSdkJNI.EngineSdkCallResultReport_biCameraOffTimeInMs_get(swigCPtr, this);
  }

  public void setBiRemoteCameraOnTimeInMs(int value) {
    EngineSdkJNI.EngineSdkCallResultReport_biRemoteCameraOnTimeInMs_set(swigCPtr, this, value);
  }

  public int getBiRemoteCameraOnTimeInMs() {
    return EngineSdkJNI.EngineSdkCallResultReport_biRemoteCameraOnTimeInMs_get(swigCPtr, this);
  }

  public void setBiRemoteCameraOffTimeInMs(int value) {
    EngineSdkJNI.EngineSdkCallResultReport_biRemoteCameraOffTimeInMs_set(swigCPtr, this, value);
  }

  public int getBiRemoteCameraOffTimeInMs() {
    return EngineSdkJNI.EngineSdkCallResultReport_biRemoteCameraOffTimeInMs_get(swigCPtr, this);
  }

  public void setBiMicOnTimeInMs(int value) {
    EngineSdkJNI.EngineSdkCallResultReport_biMicOnTimeInMs_set(swigCPtr, this, value);
  }

  public int getBiMicOnTimeInMs() {
    return EngineSdkJNI.EngineSdkCallResultReport_biMicOnTimeInMs_get(swigCPtr, this);
  }

  public void setBiMicOffTimeInMs(int value) {
    EngineSdkJNI.EngineSdkCallResultReport_biMicOffTimeInMs_set(swigCPtr, this, value);
  }

  public int getBiMicOffTimeInMs() {
    return EngineSdkJNI.EngineSdkCallResultReport_biMicOffTimeInMs_get(swigCPtr, this);
  }

  public void setBiNetTypeUnkownInMs(int value) {
    EngineSdkJNI.EngineSdkCallResultReport_biNetTypeUnkownInMs_set(swigCPtr, this, value);
  }

  public int getBiNetTypeUnkownInMs() {
    return EngineSdkJNI.EngineSdkCallResultReport_biNetTypeUnkownInMs_get(swigCPtr, this);
  }

  public void setBiNetTypeAdslInMs(int value) {
    EngineSdkJNI.EngineSdkCallResultReport_biNetTypeAdslInMs_set(swigCPtr, this, value);
  }

  public int getBiNetTypeAdslInMs() {
    return EngineSdkJNI.EngineSdkCallResultReport_biNetTypeAdslInMs_get(swigCPtr, this);
  }

  public void setBiNetTypeWifiInMs(int value) {
    EngineSdkJNI.EngineSdkCallResultReport_biNetTypeWifiInMs_set(swigCPtr, this, value);
  }

  public int getBiNetTypeWifiInMs() {
    return EngineSdkJNI.EngineSdkCallResultReport_biNetTypeWifiInMs_get(swigCPtr, this);
  }

  public void setBiNetTypeFddiInMs(int value) {
    EngineSdkJNI.EngineSdkCallResultReport_biNetTypeFddiInMs_set(swigCPtr, this, value);
  }

  public int getBiNetTypeFddiInMs() {
    return EngineSdkJNI.EngineSdkCallResultReport_biNetTypeFddiInMs_get(swigCPtr, this);
  }

  public void setBiNetTypeGprsInMs(int value) {
    EngineSdkJNI.EngineSdkCallResultReport_biNetTypeGprsInMs_set(swigCPtr, this, value);
  }

  public int getBiNetTypeGprsInMs() {
    return EngineSdkJNI.EngineSdkCallResultReport_biNetTypeGprsInMs_get(swigCPtr, this);
  }

  public void setBiNetType3gChinaUnicomInMs(int value) {
    EngineSdkJNI.EngineSdkCallResultReport_biNetType3gChinaUnicomInMs_set(swigCPtr, this, value);
  }

  public int getBiNetType3gChinaUnicomInMs() {
    return EngineSdkJNI.EngineSdkCallResultReport_biNetType3gChinaUnicomInMs_get(swigCPtr, this);
  }

  public void setBiNetType3gChinaTelecomInMs(int value) {
    EngineSdkJNI.EngineSdkCallResultReport_biNetType3gChinaTelecomInMs_set(swigCPtr, this, value);
  }

  public int getBiNetType3gChinaTelecomInMs() {
    return EngineSdkJNI.EngineSdkCallResultReport_biNetType3gChinaTelecomInMs_get(swigCPtr, this);
  }

  public void setBiNetType3gChinaMobileInMs(int value) {
    EngineSdkJNI.EngineSdkCallResultReport_biNetType3gChinaMobileInMs_set(swigCPtr, this, value);
  }

  public int getBiNetType3gChinaMobileInMs() {
    return EngineSdkJNI.EngineSdkCallResultReport_biNetType3gChinaMobileInMs_get(swigCPtr, this);
  }

  public void setBiNetType4gChinaMobileInMs(int value) {
    EngineSdkJNI.EngineSdkCallResultReport_biNetType4gChinaMobileInMs_set(swigCPtr, this, value);
  }

  public int getBiNetType4gChinaMobileInMs() {
    return EngineSdkJNI.EngineSdkCallResultReport_biNetType4gChinaMobileInMs_get(swigCPtr, this);
  }

  public void setBiTpTypeUnknownInMs(int value) {
    EngineSdkJNI.EngineSdkCallResultReport_biTpTypeUnknownInMs_set(swigCPtr, this, value);
  }

  public int getBiTpTypeUnknownInMs() {
    return EngineSdkJNI.EngineSdkCallResultReport_biTpTypeUnknownInMs_get(swigCPtr, this);
  }

  public void setBiTpTypeP2pPrivateInMs(int value) {
    EngineSdkJNI.EngineSdkCallResultReport_biTpTypeP2pPrivateInMs_set(swigCPtr, this, value);
  }

  public int getBiTpTypeP2pPrivateInMs() {
    return EngineSdkJNI.EngineSdkCallResultReport_biTpTypeP2pPrivateInMs_get(swigCPtr, this);
  }

  public void setBiTpTypeP2pPublicInMs(int value) {
    EngineSdkJNI.EngineSdkCallResultReport_biTpTypeP2pPublicInMs_set(swigCPtr, this, value);
  }

  public int getBiTpTypeP2pPublicInMs() {
    return EngineSdkJNI.EngineSdkCallResultReport_biTpTypeP2pPublicInMs_get(swigCPtr, this);
  }

  public void setBiTpTypeRelayInMs(int value) {
    EngineSdkJNI.EngineSdkCallResultReport_biTpTypeRelayInMs_set(swigCPtr, this, value);
  }

  public int getBiTpTypeRelayInMs() {
    return EngineSdkJNI.EngineSdkCallResultReport_biTpTypeRelayInMs_get(swigCPtr, this);
  }

  public void setBiCallEndingTimeInMs(int value) {
    EngineSdkJNI.EngineSdkCallResultReport_biCallEndingTimeInMs_set(swigCPtr, this, value);
  }

  public int getBiCallEndingTimeInMs() {
    return EngineSdkJNI.EngineSdkCallResultReport_biCallEndingTimeInMs_get(swigCPtr, this);
  }

  public void setBiMaxAudioDelayInMs(int value) {
    EngineSdkJNI.EngineSdkCallResultReport_biMaxAudioDelayInMs_set(swigCPtr, this, value);
  }

  public int getBiMaxAudioDelayInMs() {
    return EngineSdkJNI.EngineSdkCallResultReport_biMaxAudioDelayInMs_get(swigCPtr, this);
  }

  public void setBiMaxVideoDelayInMs(int value) {
    EngineSdkJNI.EngineSdkCallResultReport_biMaxVideoDelayInMs_set(swigCPtr, this, value);
  }

  public int getBiMaxVideoDelayInMs() {
    return EngineSdkJNI.EngineSdkCallResultReport_biMaxVideoDelayInMs_get(swigCPtr, this);
  }

  public void setBiVideoPLR(float value) {
    EngineSdkJNI.EngineSdkCallResultReport_biVideoPLR_set(swigCPtr, this, value);
  }

  public float getBiVideoPLR() {
    return EngineSdkJNI.EngineSdkCallResultReport_biVideoPLR_get(swigCPtr, this);
  }

  public void setBiAudioPLR(float value) {
    EngineSdkJNI.EngineSdkCallResultReport_biAudioPLR_set(swigCPtr, this, value);
  }

  public float getBiAudioPLR() {
    return EngineSdkJNI.EngineSdkCallResultReport_biAudioPLR_get(swigCPtr, this);
  }

  public void setM_RemoteVideoAvgBitrate(int value) {
    EngineSdkJNI.EngineSdkCallResultReport_m_RemoteVideoAvgBitrate_set(swigCPtr, this, value);
  }

  public int getM_RemoteVideoAvgBitrate() {
    return EngineSdkJNI.EngineSdkCallResultReport_m_RemoteVideoAvgBitrate_get(swigCPtr, this);
  }

  public void setBiCallerStartCallingTimeOfSecond(int value) {
    EngineSdkJNI.EngineSdkCallResultReport_biCallerStartCallingTimeOfSecond_set(swigCPtr, this, value);
  }

  public int getBiCallerStartCallingTimeOfSecond() {
    return EngineSdkJNI.EngineSdkCallResultReport_biCallerStartCallingTimeOfSecond_get(swigCPtr, this);
  }

  public void setBiCallerStartCallingTimeOfMs(int value) {
    EngineSdkJNI.EngineSdkCallResultReport_biCallerStartCallingTimeOfMs_set(swigCPtr, this, value);
  }

  public int getBiCallerStartCallingTimeOfMs() {
    return EngineSdkJNI.EngineSdkCallResultReport_biCallerStartCallingTimeOfMs_get(swigCPtr, this);
  }

  public void setBiCalleeStartRingTimeOfSecond(int value) {
    EngineSdkJNI.EngineSdkCallResultReport_biCalleeStartRingTimeOfSecond_set(swigCPtr, this, value);
  }

  public int getBiCalleeStartRingTimeOfSecond() {
    return EngineSdkJNI.EngineSdkCallResultReport_biCalleeStartRingTimeOfSecond_get(swigCPtr, this);
  }

  public void setBiCalleeStartRingTimeOfMs(int value) {
    EngineSdkJNI.EngineSdkCallResultReport_biCalleeStartRingTimeOfMs_set(swigCPtr, this, value);
  }

  public int getBiCalleeStartRingTimeOfMs() {
    return EngineSdkJNI.EngineSdkCallResultReport_biCalleeStartRingTimeOfMs_get(swigCPtr, this);
  }

  public void setBiCalleeResponseBusyTimeOfSecond(int value) {
    EngineSdkJNI.EngineSdkCallResultReport_biCalleeResponseBusyTimeOfSecond_set(swigCPtr, this, value);
  }

  public int getBiCalleeResponseBusyTimeOfSecond() {
    return EngineSdkJNI.EngineSdkCallResultReport_biCalleeResponseBusyTimeOfSecond_get(swigCPtr, this);
  }

  public void setBiCalleeResponseBusyTimeOfMs(int value) {
    EngineSdkJNI.EngineSdkCallResultReport_biCalleeResponseBusyTimeOfMs_set(swigCPtr, this, value);
  }

  public int getBiCalleeResponseBusyTimeOfMs() {
    return EngineSdkJNI.EngineSdkCallResultReport_biCalleeResponseBusyTimeOfMs_get(swigCPtr, this);
  }

  public void setBiCalleeAnswerTimeOfSecond(int value) {
    EngineSdkJNI.EngineSdkCallResultReport_biCalleeAnswerTimeOfSecond_set(swigCPtr, this, value);
  }

  public int getBiCalleeAnswerTimeOfSecond() {
    return EngineSdkJNI.EngineSdkCallResultReport_biCalleeAnswerTimeOfSecond_get(swigCPtr, this);
  }

  public void setBiCalleeAnswerTimeOfMs(int value) {
    EngineSdkJNI.EngineSdkCallResultReport_biCalleeAnswerTimeOfMs_set(swigCPtr, this, value);
  }

  public int getBiCalleeAnswerTimeOfMs() {
    return EngineSdkJNI.EngineSdkCallResultReport_biCalleeAnswerTimeOfMs_get(swigCPtr, this);
  }

  public void setBiSessionActiveTimeOfSecond(int value) {
    EngineSdkJNI.EngineSdkCallResultReport_biSessionActiveTimeOfSecond_set(swigCPtr, this, value);
  }

  public int getBiSessionActiveTimeOfSecond() {
    return EngineSdkJNI.EngineSdkCallResultReport_biSessionActiveTimeOfSecond_get(swigCPtr, this);
  }

  public void setBiSessionActiveTimeOfMs(int value) {
    EngineSdkJNI.EngineSdkCallResultReport_biSessionActiveTimeOfMs_set(swigCPtr, this, value);
  }

  public int getBiSessionActiveTimeOfMs() {
    return EngineSdkJNI.EngineSdkCallResultReport_biSessionActiveTimeOfMs_get(swigCPtr, this);
  }

  public void setBiRemoteVideoFirstFrameTimeInMs(int value) {
    EngineSdkJNI.EngineSdkCallResultReport_biRemoteVideoFirstFrameTimeInMs_set(swigCPtr, this, value);
  }

  public int getBiRemoteVideoFirstFrameTimeInMs() {
    return EngineSdkJNI.EngineSdkCallResultReport_biRemoteVideoFirstFrameTimeInMs_get(swigCPtr, this);
  }

  public void setBiSessionEndTimeOfSecond(int value) {
    EngineSdkJNI.EngineSdkCallResultReport_biSessionEndTimeOfSecond_set(swigCPtr, this, value);
  }

  public int getBiSessionEndTimeOfSecond() {
    return EngineSdkJNI.EngineSdkCallResultReport_biSessionEndTimeOfSecond_get(swigCPtr, this);
  }

  public void setBiSessionEndTimeOfMs(int value) {
    EngineSdkJNI.EngineSdkCallResultReport_biSessionEndTimeOfMs_set(swigCPtr, this, value);
  }

  public int getBiSessionEndTimeOfMs() {
    return EngineSdkJNI.EngineSdkCallResultReport_biSessionEndTimeOfMs_get(swigCPtr, this);
  }

  public void setBiMediaSetupTimeOfSecond(int value) {
    EngineSdkJNI.EngineSdkCallResultReport_biMediaSetupTimeOfSecond_set(swigCPtr, this, value);
  }

  public int getBiMediaSetupTimeOfSecond() {
    return EngineSdkJNI.EngineSdkCallResultReport_biMediaSetupTimeOfSecond_get(swigCPtr, this);
  }

  public void setBiMediaSetupTimeOfMs(int value) {
    EngineSdkJNI.EngineSdkCallResultReport_biMediaSetupTimeOfMs_set(swigCPtr, this, value);
  }

  public int getBiMediaSetupTimeOfMs() {
    return EngineSdkJNI.EngineSdkCallResultReport_biMediaSetupTimeOfMs_get(swigCPtr, this);
  }

  public void setBiLocalAccountOnlineDuringCall(boolean value) {
    EngineSdkJNI.EngineSdkCallResultReport_biLocalAccountOnlineDuringCall_set(swigCPtr, this, value);
  }

  public boolean getBiLocalAccountOnlineDuringCall() {
    return EngineSdkJNI.EngineSdkCallResultReport_biLocalAccountOnlineDuringCall_get(swigCPtr, this);
  }

  public void setBiRemoteAccountOnlineDuringCall(boolean value) {
    EngineSdkJNI.EngineSdkCallResultReport_biRemoteAccountOnlineDuringCall_set(swigCPtr, this, value);
  }

  public boolean getBiRemoteAccountOnlineDuringCall() {
    return EngineSdkJNI.EngineSdkCallResultReport_biRemoteAccountOnlineDuringCall_get(swigCPtr, this);
  }

  public void setBiRelayPath(String value) {
    EngineSdkJNI.EngineSdkCallResultReport_biRelayPath_set(swigCPtr, this, value);
  }

  public String getBiRelayPath() {
    return EngineSdkJNI.EngineSdkCallResultReport_biRelayPath_get(swigCPtr, this);
  }

  public void setBiLocalPublicIP(long value) {
    EngineSdkJNI.EngineSdkCallResultReport_biLocalPublicIP_set(swigCPtr, this, value);
  }

  public long getBiLocalPublicIP() {
    return EngineSdkJNI.EngineSdkCallResultReport_biLocalPublicIP_get(swigCPtr, this);
  }

  public void setBiAudChnEnabled(boolean value) {
    EngineSdkJNI.EngineSdkCallResultReport_biAudChnEnabled_set(swigCPtr, this, value);
  }

  public boolean getBiAudChnEnabled() {
    return EngineSdkJNI.EngineSdkCallResultReport_biAudChnEnabled_get(swigCPtr, this);
  }

  public void setBiVidChnEnabled(boolean value) {
    EngineSdkJNI.EngineSdkCallResultReport_biVidChnEnabled_set(swigCPtr, this, value);
  }

  public boolean getBiVidChnEnabled() {
    return EngineSdkJNI.EngineSdkCallResultReport_biVidChnEnabled_get(swigCPtr, this);
  }

  public void setBiVidSetup(boolean value) {
    EngineSdkJNI.EngineSdkCallResultReport_biVidSetup_set(swigCPtr, this, value);
  }

  public boolean getBiVidSetup() {
    return EngineSdkJNI.EngineSdkCallResultReport_biVidSetup_get(swigCPtr, this);
  }

  public void setBiAudSetup(boolean value) {
    EngineSdkJNI.EngineSdkCallResultReport_biAudSetup_set(swigCPtr, this, value);
  }

  public boolean getBiAudSetup() {
    return EngineSdkJNI.EngineSdkCallResultReport_biAudSetup_get(swigCPtr, this);
  }

}
