/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.kinstalk.voip.sdk;

public class EngineSdkAccountCallback {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected EngineSdkAccountCallback(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(EngineSdkAccountCallback obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        EngineSdkJNI.delete_EngineSdkAccountCallback(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    EngineSdkJNI.EngineSdkAccountCallback_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    EngineSdkJNI.EngineSdkAccountCallback_change_ownership(this, swigCPtr, true);
  }

  public void onInstanceMessageReceived(EngineSdkAccountInformation account, int im_id, String im_id_str, String im_time_str, String remote_number, String im_mime_type, String im_msg, EngineSdkMsgSender sender) {
    if (getClass() == EngineSdkAccountCallback.class) EngineSdkJNI.EngineSdkAccountCallback_onInstanceMessageReceived__SWIG_0(swigCPtr, this, EngineSdkAccountInformation.getCPtr(account), account, im_id, im_id_str, im_time_str, remote_number, im_mime_type, im_msg, sender.swigValue()); else EngineSdkJNI.EngineSdkAccountCallback_onInstanceMessageReceivedSwigExplicitEngineSdkAccountCallback__SWIG_0(swigCPtr, this, EngineSdkAccountInformation.getCPtr(account), account, im_id, im_id_str, im_time_str, remote_number, im_mime_type, im_msg, sender.swigValue());
  }

  public void onInstanceMessageReceived(EngineSdkAccountInformation account, int im_id, String im_id_str, String im_time_str, String remote_number, String im_dest_id, String im_mime_type, String im_msg, EngineSdkMsgSender sender) {
    if (getClass() == EngineSdkAccountCallback.class) EngineSdkJNI.EngineSdkAccountCallback_onInstanceMessageReceived__SWIG_1(swigCPtr, this, EngineSdkAccountInformation.getCPtr(account), account, im_id, im_id_str, im_time_str, remote_number, im_dest_id, im_mime_type, im_msg, sender.swigValue()); else EngineSdkJNI.EngineSdkAccountCallback_onInstanceMessageReceivedSwigExplicitEngineSdkAccountCallback__SWIG_1(swigCPtr, this, EngineSdkAccountInformation.getCPtr(account), account, im_id, im_id_str, im_time_str, remote_number, im_dest_id, im_mime_type, im_msg, sender.swigValue());
  }

  public void onInstanceMessageDeliveredResult(EngineSdkAccountInformation account, int im_id, String im_id_str, String im_time_str, String remote_number, String im_mime_type, String im_msg, boolean is_success, String reason, EngineSdkMsgSender sender) {
    if (getClass() == EngineSdkAccountCallback.class) EngineSdkJNI.EngineSdkAccountCallback_onInstanceMessageDeliveredResult(swigCPtr, this, EngineSdkAccountInformation.getCPtr(account), account, im_id, im_id_str, im_time_str, remote_number, im_mime_type, im_msg, is_success, reason, sender.swigValue()); else EngineSdkJNI.EngineSdkAccountCallback_onInstanceMessageDeliveredResultSwigExplicitEngineSdkAccountCallback(swigCPtr, this, EngineSdkAccountInformation.getCPtr(account), account, im_id, im_id_str, im_time_str, remote_number, im_mime_type, im_msg, is_success, reason, sender.swigValue());
  }

  public EngineSdkAccountCallback() {
    this(EngineSdkJNI.new_EngineSdkAccountCallback(), true);
    EngineSdkJNI.EngineSdkAccountCallback_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

}
