/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.kinstalk.voip.sdk;

public enum EngineSdkAccountUnregisterReason {
  ES_UREG_REASON_ON_ACC_NOT_KNOWN,
  ES_UREG_REASON_ON_ACC_TOO_MANY_CONTACTS,
  ES_UREG_REASON_ON_ACC_WRONG_PASSWORD,
  ES_UREG_REASON_ON_ACC_USER_NOT_EXIST,
  ES_UREG_REASON_ON_ACC_USER_IS_LOCKED,
  ES_UREG_REASON_ON_ACC_SERVICE_NOT_AVAILABLE,
  ES_UREG_REASON_ON_ACC_NETWORK_CONNECTION_FAILED,
  ES_UREG_REASON_ON_ACC_WRONG_VERIFICATION_CODE,
  ES_UREG_REASON_ON_ACC_SERVER_INTERNAL_ERROR,
  ES_UREG_REASON_ON_ACC_UNRESOLVEABLE_DOMAIN;

  public final int swigValue() {
    return swigValue;
  }

  public static EngineSdkAccountUnregisterReason swigToEnum(int swigValue) {
    EngineSdkAccountUnregisterReason[] swigValues = EngineSdkAccountUnregisterReason.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (EngineSdkAccountUnregisterReason swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + EngineSdkAccountUnregisterReason.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private EngineSdkAccountUnregisterReason() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private EngineSdkAccountUnregisterReason(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private EngineSdkAccountUnregisterReason(EngineSdkAccountUnregisterReason swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

