/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.kinstalk.voip.sdk;

public enum EngineSdkVideoChannelRequest {
  ES_REQUEST_ON_VIDEO_CHANNEL_TX_PAUSE,
  ES_REQUEST_ON_VIDEO_CHANNEL_TX_RESUME;

  public final int swigValue() {
    return swigValue;
  }

  public static EngineSdkVideoChannelRequest swigToEnum(int swigValue) {
    EngineSdkVideoChannelRequest[] swigValues = EngineSdkVideoChannelRequest.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (EngineSdkVideoChannelRequest swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + EngineSdkVideoChannelRequest.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private EngineSdkVideoChannelRequest() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private EngineSdkVideoChannelRequest(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private EngineSdkVideoChannelRequest(EngineSdkVideoChannelRequest swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

