/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.kinstalk.voip.sdk;

public enum EngineSdkCallState {
  ES_STATE_ON_CALL_REQUEST_CALLING_OUT,
  ES_STATE_ON_CALL_INCOMMING_CALL,
  ES_STATE_ON_CALL_ANSWERING_CALL,
  ES_STATE_ON_CALL_CALLING_OUT,
  ES_STATE_ON_CALL_RINGBACK_TONE,
  ES_STATE_ON_CALL_IN_ACTIVE_SESSION,
  ES_STATE_ON_CALL_CALL_ENDING,
  ES_STATE_ON_CALL_CALL_ENDED;

  public final int swigValue() {
    return swigValue;
  }

  public static EngineSdkCallState swigToEnum(int swigValue) {
    EngineSdkCallState[] swigValues = EngineSdkCallState.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (EngineSdkCallState swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + EngineSdkCallState.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private EngineSdkCallState() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private EngineSdkCallState(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private EngineSdkCallState(EngineSdkCallState swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

