/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.kinstalk.voip.sdk;

public interface EngineSdkConstants {
  public final static int ES_SUCCESS = EngineSdkJNI.ES_SUCCESS_get();
  public final static int ES_FAILURE = EngineSdkJNI.ES_FAILURE_get();
  public final static int ES_TRUE = EngineSdkJNI.ES_TRUE_get();
  public final static int ES_FALSE = EngineSdkJNI.ES_FALSE_get();
  public final static int ES_NULL = EngineSdkJNI.ES_NULL_get();
  public final static int ES_MD5STRLEN = EngineSdkJNI.ES_MD5STRLEN_get();
  public final static int ES_ACC_MAX_PROXIES = EngineSdkJNI.ES_ACC_MAX_PROXIES_get();
}
