/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.kinstalk.voip.sdk;

public class EngineSdkEngineConfiguration {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected EngineSdkEngineConfiguration(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(EngineSdkEngineConfiguration obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        EngineSdkJNI.delete_EngineSdkEngineConfiguration(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    EngineSdkJNI.EngineSdkEngineConfiguration_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    EngineSdkJNI.EngineSdkEngineConfiguration_change_ownership(this, swigCPtr, true);
  }

  public EngineSdkEngineConfiguration() {
    this(EngineSdkJNI.new_EngineSdkEngineConfiguration(), true);
    EngineSdkJNI.EngineSdkEngineConfiguration_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public void setEngineCallback(EngineSdkEngineCallback value) {
    EngineSdkJNI.EngineSdkEngineConfiguration_engineCallback_set(swigCPtr, this, EngineSdkEngineCallback.getCPtr(value), value);
  }

  public EngineSdkEngineCallback getEngineCallback() {
    long cPtr = EngineSdkJNI.EngineSdkEngineConfiguration_engineCallback_get(swigCPtr, this);
    return (cPtr == 0) ? null : new EngineSdkEngineCallback(cPtr, false);
  }

  public void setAndroidActivityContext(Object value) {
    EngineSdkJNI.EngineSdkEngineConfiguration_androidActivityContext_set(swigCPtr, this, value);
  }

  public Object getAndroidActivityContext() {
    return EngineSdkJNI.EngineSdkEngineConfiguration_androidActivityContext_get(swigCPtr, this);
}

  public void setServerType(EngineSdkServerType value) {
    EngineSdkJNI.EngineSdkEngineConfiguration_serverType_set(swigCPtr, this, value.swigValue());
  }

  public EngineSdkServerType getServerType() {
    return EngineSdkServerType.swigToEnum(EngineSdkJNI.EngineSdkEngineConfiguration_serverType_get(swigCPtr, this));
  }

  public void setMaximalTransmitVideoResolutionWidth(int value) {
    EngineSdkJNI.EngineSdkEngineConfiguration_maximalTransmitVideoResolutionWidth_set(swigCPtr, this, value);
  }

  public int getMaximalTransmitVideoResolutionWidth() {
    return EngineSdkJNI.EngineSdkEngineConfiguration_maximalTransmitVideoResolutionWidth_get(swigCPtr, this);
  }

  public void setMaximalTransmitVideoResolutionHeight(int value) {
    EngineSdkJNI.EngineSdkEngineConfiguration_maximalTransmitVideoResolutionHeight_set(swigCPtr, this, value);
  }

  public int getMaximalTransmitVideoResolutionHeight() {
    return EngineSdkJNI.EngineSdkEngineConfiguration_maximalTransmitVideoResolutionHeight_get(swigCPtr, this);
  }

  public void setMaximalReceiveVideoResolutionWidth(int value) {
    EngineSdkJNI.EngineSdkEngineConfiguration_maximalReceiveVideoResolutionWidth_set(swigCPtr, this, value);
  }

  public int getMaximalReceiveVideoResolutionWidth() {
    return EngineSdkJNI.EngineSdkEngineConfiguration_maximalReceiveVideoResolutionWidth_get(swigCPtr, this);
  }

  public void setMaximalReceiveVideoResolutionHeight(int value) {
    EngineSdkJNI.EngineSdkEngineConfiguration_maximalReceiveVideoResolutionHeight_set(swigCPtr, this, value);
  }

  public int getMaximalReceiveVideoResolutionHeight() {
    return EngineSdkJNI.EngineSdkEngineConfiguration_maximalReceiveVideoResolutionHeight_get(swigCPtr, this);
  }

  public void setProductModel(String value) {
    EngineSdkJNI.EngineSdkEngineConfiguration_productModel_set(swigCPtr, this, value);
  }

  public String getProductModel() {
    return EngineSdkJNI.EngineSdkEngineConfiguration_productModel_get(swigCPtr, this);
  }

  public void setDeviceIdentification(String value) {
    EngineSdkJNI.EngineSdkEngineConfiguration_deviceIdentification_set(swigCPtr, this, value);
  }

  public String getDeviceIdentification() {
    return EngineSdkJNI.EngineSdkEngineConfiguration_deviceIdentification_get(swigCPtr, this);
  }

  public void setUserAgent(String value) {
    EngineSdkJNI.EngineSdkEngineConfiguration_userAgent_set(swigCPtr, this, value);
  }

  public String getUserAgent() {
    return EngineSdkJNI.EngineSdkEngineConfiguration_userAgent_get(swigCPtr, this);
  }

  public void setDnsServerIPAdress(String value) {
    EngineSdkJNI.EngineSdkEngineConfiguration_dnsServerIPAdress_set(swigCPtr, this, value);
  }

  public String getDnsServerIPAdress() {
    return EngineSdkJNI.EngineSdkEngineConfiguration_dnsServerIPAdress_get(swigCPtr, this);
  }

  public void setDeviceCPUInformation(EngineSdkCpuInformation value) {
    EngineSdkJNI.EngineSdkEngineConfiguration_deviceCPUInformation_set(swigCPtr, this, EngineSdkCpuInformation.getCPtr(value), value);
  }

  public EngineSdkCpuInformation getDeviceCPUInformation() {
    long cPtr = EngineSdkJNI.EngineSdkEngineConfiguration_deviceCPUInformation_get(swigCPtr, this);
    return (cPtr == 0) ? null : new EngineSdkCpuInformation(cPtr, false);
  }

  public void setDeviceOperatingSystemType(EngineSdkOperatingSystemType value) {
    EngineSdkJNI.EngineSdkEngineConfiguration_deviceOperatingSystemType_set(swigCPtr, this, value.swigValue());
  }

  public EngineSdkOperatingSystemType getDeviceOperatingSystemType() {
    return EngineSdkOperatingSystemType.swigToEnum(EngineSdkJNI.EngineSdkEngineConfiguration_deviceOperatingSystemType_get(swigCPtr, this));
  }

  public void setDeviceCurrentNetworkType(EngineSdkNetworkType value) {
    EngineSdkJNI.EngineSdkEngineConfiguration_deviceCurrentNetworkType_set(swigCPtr, this, value.swigValue());
  }

  public EngineSdkNetworkType getDeviceCurrentNetworkType() {
    return EngineSdkNetworkType.swigToEnum(EngineSdkJNI.EngineSdkEngineConfiguration_deviceCurrentNetworkType_get(swigCPtr, this));
  }

  public void setFileSystemMounted(boolean value) {
    EngineSdkJNI.EngineSdkEngineConfiguration_fileSystemMounted_set(swigCPtr, this, value);
  }

  public boolean getFileSystemMounted() {
    return EngineSdkJNI.EngineSdkEngineConfiguration_fileSystemMounted_get(swigCPtr, this);
  }

  public void setLogLevel(int value) {
    EngineSdkJNI.EngineSdkEngineConfiguration_logLevel_set(swigCPtr, this, value);
  }

  public int getLogLevel() {
    return EngineSdkJNI.EngineSdkEngineConfiguration_logLevel_get(swigCPtr, this);
  }

  public void setLogPathWithFileName(String value) {
    EngineSdkJNI.EngineSdkEngineConfiguration_logPathWithFileName_set(swigCPtr, this, value);
  }

  public String getLogPathWithFileName() {
    return EngineSdkJNI.EngineSdkEngineConfiguration_logPathWithFileName_get(swigCPtr, this);
  }

  public void setSipTokenHeader(String value) {
    EngineSdkJNI.EngineSdkEngineConfiguration_sipTokenHeader_set(swigCPtr, this, value);
  }

  public String getSipTokenHeader() {
    return EngineSdkJNI.EngineSdkEngineConfiguration_sipTokenHeader_get(swigCPtr, this);
  }

  public void setGslbCachePathWithFileName(String value) {
    EngineSdkJNI.EngineSdkEngineConfiguration_gslbCachePathWithFileName_set(swigCPtr, this, value);
  }

  public String getGslbCachePathWithFileName() {
    return EngineSdkJNI.EngineSdkEngineConfiguration_gslbCachePathWithFileName_get(swigCPtr, this);
  }

  public void setGslbIPFromServer(String value) {
    EngineSdkJNI.EngineSdkEngineConfiguration_gslbIPFromServer_set(swigCPtr, this, value);
  }

  public String getGslbIPFromServer() {
    return EngineSdkJNI.EngineSdkEngineConfiguration_gslbIPFromServer_get(swigCPtr, this);
  }

  public void setEdgeProxyIPFromServer(String value) {
    EngineSdkJNI.EngineSdkEngineConfiguration_edgeProxyIPFromServer_set(swigCPtr, this, value);
  }

  public String getEdgeProxyIPFromServer() {
    return EngineSdkJNI.EngineSdkEngineConfiguration_edgeProxyIPFromServer_get(swigCPtr, this);
  }

  public void setRelayIPFromServer(String value) {
    EngineSdkJNI.EngineSdkEngineConfiguration_relayIPFromServer_set(swigCPtr, this, value);
  }

  public String getRelayIPFromServer() {
    return EngineSdkJNI.EngineSdkEngineConfiguration_relayIPFromServer_get(swigCPtr, this);
  }

  public void setAudioMediaChannelMode(EngineSdkMediaChannelSetupMode value) {
    EngineSdkJNI.EngineSdkEngineConfiguration_audioMediaChannelMode_set(swigCPtr, this, value.swigValue());
  }

  public EngineSdkMediaChannelSetupMode getAudioMediaChannelMode() {
    return EngineSdkMediaChannelSetupMode.swigToEnum(EngineSdkJNI.EngineSdkEngineConfiguration_audioMediaChannelMode_get(swigCPtr, this));
  }

  public void setMainVideoMediaChannelMode(EngineSdkMediaChannelSetupMode value) {
    EngineSdkJNI.EngineSdkEngineConfiguration_mainVideoMediaChannelMode_set(swigCPtr, this, value.swigValue());
  }

  public EngineSdkMediaChannelSetupMode getMainVideoMediaChannelMode() {
    return EngineSdkMediaChannelSetupMode.swigToEnum(EngineSdkJNI.EngineSdkEngineConfiguration_mainVideoMediaChannelMode_get(swigCPtr, this));
  }

  public void setSecondVideoMediaChannelMode(EngineSdkMediaChannelSetupMode value) {
    EngineSdkJNI.EngineSdkEngineConfiguration_secondVideoMediaChannelMode_set(swigCPtr, this, value.swigValue());
  }

  public EngineSdkMediaChannelSetupMode getSecondVideoMediaChannelMode() {
    return EngineSdkMediaChannelSetupMode.swigToEnum(EngineSdkJNI.EngineSdkEngineConfiguration_secondVideoMediaChannelMode_get(swigCPtr, this));
  }

  public void setDataMediaChannelMode(EngineSdkMediaChannelSetupMode value) {
    EngineSdkJNI.EngineSdkEngineConfiguration_dataMediaChannelMode_set(swigCPtr, this, value.swigValue());
  }

  public EngineSdkMediaChannelSetupMode getDataMediaChannelMode() {
    return EngineSdkMediaChannelSetupMode.swigToEnum(EngineSdkJNI.EngineSdkEngineConfiguration_dataMediaChannelMode_get(swigCPtr, this));
  }

  public void setEngineWorkingMode(EngineSdkEngineWorkingMode value) {
    EngineSdkJNI.EngineSdkEngineConfiguration_engineWorkingMode_set(swigCPtr, this, value.swigValue());
  }

  public EngineSdkEngineWorkingMode getEngineWorkingMode() {
    return EngineSdkEngineWorkingMode.swigToEnum(EngineSdkJNI.EngineSdkEngineConfiguration_engineWorkingMode_get(swigCPtr, this));
  }

  public void setAudioOutputMode(EngineSdkAudioOutputMode value) {
    EngineSdkJNI.EngineSdkEngineConfiguration_audioOutputMode_set(swigCPtr, this, value.swigValue());
  }

  public EngineSdkAudioOutputMode getAudioOutputMode() {
    return EngineSdkAudioOutputMode.swigToEnum(EngineSdkJNI.EngineSdkEngineConfiguration_audioOutputMode_get(swigCPtr, this));
  }

  public void setEngineDNSMode(EngineSdkDNSMode value) {
    EngineSdkJNI.EngineSdkEngineConfiguration_engineDNSMode_set(swigCPtr, this, value.swigValue());
  }

  public EngineSdkDNSMode getEngineDNSMode() {
    return EngineSdkDNSMode.swigToEnum(EngineSdkJNI.EngineSdkEngineConfiguration_engineDNSMode_get(swigCPtr, this));
  }

  public EngineSdkEngineConfiguration clone() {
    long cPtr = EngineSdkJNI.EngineSdkEngineConfiguration_clone(swigCPtr, this);
    return (cPtr == 0) ? null : new EngineSdkEngineConfiguration(cPtr, false);
  }

}
