/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.kinstalk.voip.sdk;

public class EngineSdkEngineAudioControlParameter {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected EngineSdkEngineAudioControlParameter(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(EngineSdkEngineAudioControlParameter obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        EngineSdkJNI.delete_EngineSdkEngineAudioControlParameter(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setReservedParameter(long value) {
    EngineSdkJNI.EngineSdkEngineAudioControlParameter_reservedParameter_set(swigCPtr, this, value);
  }

  public long getReservedParameter() {
    return EngineSdkJNI.EngineSdkEngineAudioControlParameter_reservedParameter_get(swigCPtr, this);
  }

  public EngineSdkEngineAudioControlParameter() {
    this(EngineSdkJNI.new_EngineSdkEngineAudioControlParameter(), true);
  }

}
