/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.kinstalk.voip.sdk;

public enum EngineSdkServerType {
  ES_OFFICIAL_ONLINE_SERVER,
  ES_TESTER_TESTING_SERVER,
  ES_ENGINEER_DEVELOPMENT_SERVER,
  ES_PAPA_ONLINE_SERVER,
  ES_QINYOUYUE_ONLINE_SERVER,
  ES_QINYOUYUE_TEST_SERVER,
  ES_QINYOUYUE_DEV_SERVER;

  public final int swigValue() {
    return swigValue;
  }

  public static EngineSdkServerType swigToEnum(int swigValue) {
    EngineSdkServerType[] swigValues = EngineSdkServerType.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (EngineSdkServerType swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + EngineSdkServerType.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private EngineSdkServerType() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private EngineSdkServerType(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private EngineSdkServerType(EngineSdkServerType swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

