/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.kinstalk.voip.sdk;

public enum EngineSdkCPUInstruction {
  ES_CPU_INSTRUCTION_UNKNOWN,
  ES_CPU_INSTRUCTION_NEON,
  ES_CPU_INSTRUCTION_ARMV5TE,
  ES_CPU_INSTRUCTION_ARMV6,
  ES_CPU_INSTRUCTION_ARMV6T2,
  ES_CPU_INSTRUCTION_INTELX86;

  public final int swigValue() {
    return swigValue;
  }

  public static EngineSdkCPUInstruction swigToEnum(int swigValue) {
    EngineSdkCPUInstruction[] swigValues = EngineSdkCPUInstruction.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (EngineSdkCPUInstruction swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + EngineSdkCPUInstruction.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private EngineSdkCPUInstruction() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private EngineSdkCPUInstruction(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private EngineSdkCPUInstruction(EngineSdkCPUInstruction swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

