/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.kinstalk.voip.sdk;

public enum EngineSdkEngineState {
  ES_STATE_ON_ENGINE_UNINITIALIZED,
  ES_STATE_ON_ENGINE_INITIALIZED,
  ES_STATE_ON_ENGINE_DISCONNECTED,
  ES_STATE_ON_ENGINE_CONNECTED;

  public final int swigValue() {
    return swigValue;
  }

  public static EngineSdkEngineState swigToEnum(int swigValue) {
    EngineSdkEngineState[] swigValues = EngineSdkEngineState.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (EngineSdkEngineState swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + EngineSdkEngineState.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private EngineSdkEngineState() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private EngineSdkEngineState(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private EngineSdkEngineState(EngineSdkEngineState swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

