/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.kinstalk.voip.sdk;

public enum EngineSdkDNSMode {
  ES_ENGINE_DNS_BOTH_SYNC_ASYNC,
  ES_ENGINE_DNS_SYNC_ONLY,
  ES_ENGINE_DNS_ASYNC_ONLY;

  public final int swigValue() {
    return swigValue;
  }

  public static EngineSdkDNSMode swigToEnum(int swigValue) {
    EngineSdkDNSMode[] swigValues = EngineSdkDNSMode.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (EngineSdkDNSMode swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + EngineSdkDNSMode.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private EngineSdkDNSMode() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private EngineSdkDNSMode(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private EngineSdkDNSMode(EngineSdkDNSMode swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

