/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.kinstalk.voip.sdk;

public class EngineSdkVideoChannelConfiguration {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected EngineSdkVideoChannelConfiguration(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(EngineSdkVideoChannelConfiguration obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        EngineSdkJNI.delete_EngineSdkVideoChannelConfiguration(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setTransmitingVideoFormat(EngineSdkVideoFrameFormat value) {
    EngineSdkJNI.EngineSdkVideoChannelConfiguration_transmitingVideoFormat_set(swigCPtr, this, EngineSdkVideoFrameFormat.getCPtr(value), value);
  }

  public EngineSdkVideoFrameFormat getTransmitingVideoFormat() {
    long cPtr = EngineSdkJNI.EngineSdkVideoChannelConfiguration_transmitingVideoFormat_get(swigCPtr, this);
    return (cPtr == 0) ? null : new EngineSdkVideoFrameFormat(cPtr, false);
  }

  public void setReceivingVideoFormat(EngineSdkVideoFrameFormat value) {
    EngineSdkJNI.EngineSdkVideoChannelConfiguration_receivingVideoFormat_set(swigCPtr, this, EngineSdkVideoFrameFormat.getCPtr(value), value);
  }

  public EngineSdkVideoFrameFormat getReceivingVideoFormat() {
    long cPtr = EngineSdkJNI.EngineSdkVideoChannelConfiguration_receivingVideoFormat_get(swigCPtr, this);
    return (cPtr == 0) ? null : new EngineSdkVideoFrameFormat(cPtr, false);
  }

  public EngineSdkVideoChannelConfiguration() {
    this(EngineSdkJNI.new_EngineSdkVideoChannelConfiguration(), true);
  }

}
