/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.kinstalk.voip.sdk;

public class EngineSdkMediaSecondVideoCallback {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected EngineSdkMediaSecondVideoCallback(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(EngineSdkMediaSecondVideoCallback obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        EngineSdkJNI.delete_EngineSdkMediaSecondVideoCallback(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    EngineSdkJNI.EngineSdkMediaSecondVideoCallback_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    EngineSdkJNI.EngineSdkMediaSecondVideoCallback_change_ownership(this, swigCPtr, true);
  }

  public void onSecondVideoChannelDataReceived(EngineSdkCallInformation p_call, EngineSdkVideoPixelFormat p_format, int w, int h, char rotation, String pcDataBuf, int iDataLen) {
    if (getClass() == EngineSdkMediaSecondVideoCallback.class) EngineSdkJNI.EngineSdkMediaSecondVideoCallback_onSecondVideoChannelDataReceived(swigCPtr, this, EngineSdkCallInformation.getCPtr(p_call), p_call, p_format.swigValue(), w, h, rotation, pcDataBuf, iDataLen); else EngineSdkJNI.EngineSdkMediaSecondVideoCallback_onSecondVideoChannelDataReceivedSwigExplicitEngineSdkMediaSecondVideoCallback(swigCPtr, this, EngineSdkCallInformation.getCPtr(p_call), p_call, p_format.swigValue(), w, h, rotation, pcDataBuf, iDataLen);
  }

  public void onSecondVideoChannelStateChanged(EngineSdkCallInformation p_call) {
    if (getClass() == EngineSdkMediaSecondVideoCallback.class) EngineSdkJNI.EngineSdkMediaSecondVideoCallback_onSecondVideoChannelStateChanged(swigCPtr, this, EngineSdkCallInformation.getCPtr(p_call), p_call); else EngineSdkJNI.EngineSdkMediaSecondVideoCallback_onSecondVideoChannelStateChangedSwigExplicitEngineSdkMediaSecondVideoCallback(swigCPtr, this, EngineSdkCallInformation.getCPtr(p_call), p_call);
  }

  public EngineSdkMediaSecondVideoCallback() {
    this(EngineSdkJNI.new_EngineSdkMediaSecondVideoCallback(), true);
    EngineSdkJNI.EngineSdkMediaSecondVideoCallback_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

}
