/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.kinstalk.voip.sdk;

public enum EngineSdkNetworkType {
  ES_NETWORK_TYPE_UNKNOWN,
  ES_NETWORK_TYPE_ADSL,
  ES_NETWORK_TYPE_WIFI,
  ES_NETWORK_TYPE_FDDI,
  ES_NETWORK_TYPE_GPRS,
  ES_NETWORK_TYPE_CHINA_UNICOM_3G,
  ES_NETWORK_TYPE_CHINA_TELECOM_3G,
  ES_NETWORK_TYPE_CHINA_MOBILE_3G,
  ES_NETWORK_TYPE_CHINA_MOBILE_4G;

  public final int swigValue() {
    return swigValue;
  }

  public static EngineSdkNetworkType swigToEnum(int swigValue) {
    EngineSdkNetworkType[] swigValues = EngineSdkNetworkType.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (EngineSdkNetworkType swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + EngineSdkNetworkType.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private EngineSdkNetworkType() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private EngineSdkNetworkType(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private EngineSdkNetworkType(EngineSdkNetworkType swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

