/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.kinstalk.voip.sdk;

public class EngineSdkAccountInformation {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected EngineSdkAccountInformation(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(EngineSdkAccountInformation obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        EngineSdkJNI.delete_EngineSdkAccountInformation(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    EngineSdkJNI.EngineSdkAccountInformation_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    EngineSdkJNI.EngineSdkAccountInformation_change_ownership(this, swigCPtr, true);
  }

  public EngineSdkAccountInformation() {
    this(EngineSdkJNI.new_EngineSdkAccountInformation(), true);
    EngineSdkJNI.EngineSdkAccountInformation_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public void setAccountConfiguration(EngineSdkAccountConfiguration value) {
    EngineSdkJNI.EngineSdkAccountInformation_accountConfiguration_set(swigCPtr, this, EngineSdkAccountConfiguration.getCPtr(value), value);
  }

  public EngineSdkAccountConfiguration getAccountConfiguration() {
    long cPtr = EngineSdkJNI.EngineSdkAccountInformation_accountConfiguration_get(swigCPtr, this);
    return (cPtr == 0) ? null : new EngineSdkAccountConfiguration(cPtr, false);
  }

  public void setAccountState(EngineSdkAccountState value) {
    EngineSdkJNI.EngineSdkAccountInformation_accountState_set(swigCPtr, this, value.swigValue());
  }

  public EngineSdkAccountState getAccountState() {
    return EngineSdkAccountState.swigToEnum(EngineSdkJNI.EngineSdkAccountInformation_accountState_get(swigCPtr, this));
  }

  public void setAccountUnregisterReason(EngineSdkAccountUnregisterReason value) {
    EngineSdkJNI.EngineSdkAccountInformation_accountUnregisterReason_set(swigCPtr, this, value.swigValue());
  }

  public EngineSdkAccountUnregisterReason getAccountUnregisterReason() {
    return EngineSdkAccountUnregisterReason.swigToEnum(EngineSdkJNI.EngineSdkAccountInformation_accountUnregisterReason_get(swigCPtr, this));
  }

  public int sendInstanceMessage(String remote_number, String im_mime_type, String im_msg, EngineSdkMsgSender sender) {
    return EngineSdkJNI.EngineSdkAccountInformation_sendInstanceMessage(swigCPtr, this, remote_number, im_mime_type, im_msg, sender.swigValue());
  }

  public EngineSdkAccountInformation clone() {
    long cPtr = EngineSdkJNI.EngineSdkAccountInformation_clone(swigCPtr, this);
    return (cPtr == 0) ? null : new EngineSdkAccountInformation(cPtr, false);
  }

}
