/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.kinstalk.voip.sdk;

public enum EngineSdkInSessionNetworkQualityIndication {
  ES_INDICATION_ON_CALL_NETWORK_VIDEO_NORMAL,
  ES_INDICATION_ON_CALL_NETWORK_VIDEO_BAD,
  ES_INDICATION_ON_CALL_NETWORK_VIDEO_OFF,

  ES_INDICATION_ON_CALL_NETWORK_SESSION_END,
  ES_INDICATION_ON_CALL_NETWORK_AUDIO_NORMAL,
  ES_INDICATION_ON_CALL_NETWORK_AUDIO_BAD,
  ES_INDICATION_ON_CALL_NETWORK_AUDIO_OFF,
  ES_INDICATION_ON_CALL_NETWORK_AUDIO_END;
  public final int swigValue() {
    return swigValue;
  }

  public static EngineSdkInSessionNetworkQualityIndication swigToEnum(int swigValue) {
    EngineSdkInSessionNetworkQualityIndication[] swigValues = EngineSdkInSessionNetworkQualityIndication.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (EngineSdkInSessionNetworkQualityIndication swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + EngineSdkInSessionNetworkQualityIndication.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private EngineSdkInSessionNetworkQualityIndication() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private EngineSdkInSessionNetworkQualityIndication(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private EngineSdkInSessionNetworkQualityIndication(EngineSdkInSessionNetworkQualityIndication swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

