/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.kinstalk.voip.sdk;

public class EngineSdkMediaAudioCallback {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected EngineSdkMediaAudioCallback(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(EngineSdkMediaAudioCallback obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        EngineSdkJNI.delete_EngineSdkMediaAudioCallback(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    EngineSdkJNI.EngineSdkMediaAudioCallback_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    EngineSdkJNI.EngineSdkMediaAudioCallback_change_ownership(this, swigCPtr, true);
  }

  public void onAudioTransmitingChannelStateChange(EngineSdkCallInformation callInfo) {
    if (getClass() == EngineSdkMediaAudioCallback.class) EngineSdkJNI.EngineSdkMediaAudioCallback_onAudioTransmitingChannelStateChange(swigCPtr, this, EngineSdkCallInformation.getCPtr(callInfo), callInfo); else EngineSdkJNI.EngineSdkMediaAudioCallback_onAudioTransmitingChannelStateChangeSwigExplicitEngineSdkMediaAudioCallback(swigCPtr, this, EngineSdkCallInformation.getCPtr(callInfo), callInfo);
  }

  public void onAudioRecevingChannelStateChange(EngineSdkCallInformation callInfo) {
    if (getClass() == EngineSdkMediaAudioCallback.class) EngineSdkJNI.EngineSdkMediaAudioCallback_onAudioRecevingChannelStateChange(swigCPtr, this, EngineSdkCallInformation.getCPtr(callInfo), callInfo); else EngineSdkJNI.EngineSdkMediaAudioCallback_onAudioRecevingChannelStateChangeSwigExplicitEngineSdkMediaAudioCallback(swigCPtr, this, EngineSdkCallInformation.getCPtr(callInfo), callInfo);
  }

  public EngineSdkMediaAudioCallback() {
    this(EngineSdkJNI.new_EngineSdkMediaAudioCallback(), true);
    EngineSdkJNI.EngineSdkMediaAudioCallback_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

}
