/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.kinstalk.voip.sdk;

public enum EngineSdkDataChannelState {
  ES_STATE_ON_DATA_CHANNEL_CREATED,
  ES_STATE_ON_DATA_CHANNEL_DESTROYED,
  ES_STATE_ON_DATA_CHANNEL_BINDING,
  ES_STATE_ON_DATA_CHANNEL_ACCEPTED,
  ES_STATE_ON_DATA_CHANNEL_REJECTED;

  public final int swigValue() {
    return swigValue;
  }

  public static EngineSdkDataChannelState swigToEnum(int swigValue) {
    EngineSdkDataChannelState[] swigValues = EngineSdkDataChannelState.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (EngineSdkDataChannelState swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + EngineSdkDataChannelState.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private EngineSdkDataChannelState() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private EngineSdkDataChannelState(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private EngineSdkDataChannelState(EngineSdkDataChannelState swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

