/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.kinstalk.voip.sdk;

public class EngineSdkVideoFrameFormat {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected EngineSdkVideoFrameFormat(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(EngineSdkVideoFrameFormat obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        EngineSdkJNI.delete_EngineSdkVideoFrameFormat(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setWidth(int value) {
    EngineSdkJNI.EngineSdkVideoFrameFormat_width_set(swigCPtr, this, value);
  }

  public int getWidth() {
    return EngineSdkJNI.EngineSdkVideoFrameFormat_width_get(swigCPtr, this);
  }

  public void setHeight(int value) {
    EngineSdkJNI.EngineSdkVideoFrameFormat_height_set(swigCPtr, this, value);
  }

  public int getHeight() {
    return EngineSdkJNI.EngineSdkVideoFrameFormat_height_get(swigCPtr, this);
  }

  public void setSize(int value) {
    EngineSdkJNI.EngineSdkVideoFrameFormat_size_set(swigCPtr, this, value);
  }

  public int getSize() {
    return EngineSdkJNI.EngineSdkVideoFrameFormat_size_get(swigCPtr, this);
  }

  public void setRotation(char value) {
    EngineSdkJNI.EngineSdkVideoFrameFormat_rotation_set(swigCPtr, this, value);
  }

  public char getRotation() {
    return EngineSdkJNI.EngineSdkVideoFrameFormat_rotation_get(swigCPtr, this);
  }

  public void setFormat(EngineSdkVideoPixelFormat value) {
    EngineSdkJNI.EngineSdkVideoFrameFormat_format_set(swigCPtr, this, value.swigValue());
  }

  public EngineSdkVideoPixelFormat getFormat() {
    return EngineSdkVideoPixelFormat.swigToEnum(EngineSdkJNI.EngineSdkVideoFrameFormat_format_get(swigCPtr, this));
  }

  public void setFrameRate(float value) {
    EngineSdkJNI.EngineSdkVideoFrameFormat_frameRate_set(swigCPtr, this, value);
  }

  public float getFrameRate() {
    return EngineSdkJNI.EngineSdkVideoFrameFormat_frameRate_get(swigCPtr, this);
  }

  public EngineSdkVideoFrameFormat() {
    this(EngineSdkJNI.new_EngineSdkVideoFrameFormat(), true);
  }

}
