/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.kinstalk.voip.sdk;

public enum EngineSdkVideoPixelFormat {
  ES_PIXEL_FORMAT_NONE,
  ES_PIXEL_FORMAT_RGBA,
  ES_PIXEL_FORMAT_BGR24,
  ES_PIXEL_FORMAT_BGRA,
  ES_PIXEL_FORMAT_YUYV422,
  ES_PIXEL_FORMAT_UYVY422,
  ES_PIXEL_FORMAT_YUV420P,
  ES_PIXEL_FORMAT_YUV422P,
  ES_PIXEL_FORMAT_NV21,
  ES_PIXEL_FORMAT_YUVJ420P,
  ES_PIXEL_FORMAT_YUVJ422P;

  public final int swigValue() {
    return swigValue;
  }

  public static EngineSdkVideoPixelFormat swigToEnum(int swigValue) {
    EngineSdkVideoPixelFormat[] swigValues = EngineSdkVideoPixelFormat.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (EngineSdkVideoPixelFormat swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + EngineSdkVideoPixelFormat.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private EngineSdkVideoPixelFormat() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private EngineSdkVideoPixelFormat(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private EngineSdkVideoPixelFormat(EngineSdkVideoPixelFormat swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

