/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.kinstalk.voip.sdk;

public class EngineSdkDataChannelConfiguration {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected EngineSdkDataChannelConfiguration(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(EngineSdkDataChannelConfiguration obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        EngineSdkJNI.delete_EngineSdkDataChannelConfiguration(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setCall_id(int value) {
    EngineSdkJNI.EngineSdkDataChannelConfiguration_call_id_set(swigCPtr, this, value);
  }

  public int getCall_id() {
    return EngineSdkJNI.EngineSdkDataChannelConfiguration_call_id_get(swigCPtr, this);
  }

  public void setCallLocalToken(long value) {
    EngineSdkJNI.EngineSdkDataChannelConfiguration_callLocalToken_set(swigCPtr, this, value);
  }

  public long getCallLocalToken() {
    return EngineSdkJNI.EngineSdkDataChannelConfiguration_callLocalToken_get(swigCPtr, this);
  }

  public void setServiceName(String value) {
    EngineSdkJNI.EngineSdkDataChannelConfiguration_serviceName_set(swigCPtr, this, value);
  }

  public String getServiceName() {
    return EngineSdkJNI.EngineSdkDataChannelConfiguration_serviceName_get(swigCPtr, this);
  }

  public EngineSdkDataChannelConfiguration() {
    this(EngineSdkJNI.new_EngineSdkDataChannelConfiguration(), true);
  }

}
