/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.kinstalk.voip.sdk;

public class EngineSdkBiExceptionCallback {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected EngineSdkBiExceptionCallback(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(EngineSdkBiExceptionCallback obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        EngineSdkJNI.delete_EngineSdkBiExceptionCallback(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public EngineSdkBiExceptionCallback() {
    this(EngineSdkJNI.new_EngineSdkBiExceptionCallback(), true);
  }

  public void onThrowBiException(EngineSdkCallInformation callInfo, EngineSdkBiException biException, int detail) {
    EngineSdkJNI.EngineSdkBiExceptionCallback_onThrowBiException(swigCPtr, this, EngineSdkCallInformation.getCPtr(callInfo), callInfo, biException.swigValue(), detail);
  }

}
