/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.kinstalk.voip.sdk;

public class EngineSdk implements EngineSdkConstants {
  public static boolean initializeEngine(EngineSdkEngineConfiguration engineConf, Object androidActivityContext) {
    return EngineSdkJNI.initializeEngine(EngineSdkEngineConfiguration.getCPtr(engineConf), engineConf, androidActivityContext);
  }

  public static boolean destroyEngine() {
    return EngineSdkJNI.destroyEngine();
  }

  public static boolean setEngineWorkingMode(EngineSdkEngineWorkingMode engineWorkingMode) {
    return EngineSdkJNI.setEngineWorkingMode(engineWorkingMode.swigValue());
  }

  public static boolean updateEngineTokenHeader(String token, String realm) {
    return EngineSdkJNI.updateEngineTokenHeader(token, realm);
  }

  public static boolean updateEngineConfiguration(EngineSdkEngineConfiguration engineConfig) {
    return EngineSdkJNI.updateEngineConfiguration(EngineSdkEngineConfiguration.getCPtr(engineConfig), engineConfig);
  }

  public static boolean informFileSystemHaveMounted(boolean isMounted) {
    return EngineSdkJNI.informFileSystemHaveMounted(isMounted);
  }

  public static boolean addOneClientSupportFeatureName(String name) {
    return EngineSdkJNI.addOneClientSupportFeatureName(name);
  }

  public static boolean informSystemNetworkResumed(EngineSdkNetworkType CurrentNetworkType) {
    return EngineSdkJNI.informSystemNetworkResumed(CurrentNetworkType.swigValue());
  }

  public static boolean setSystemSupportedAudioCaptureSamplingRate(short sampling) {
    return EngineSdkJNI.setSystemSupportedAudioCaptureSamplingRate(sampling);
  }

  public static boolean addOrUpdateAccount(EngineSdkAccountConfiguration accountConf) {
    return EngineSdkJNI.addOrUpdateAccount(EngineSdkAccountConfiguration.getCPtr(accountConf), accountConf);
  }

  public static boolean deleteAccount(EngineSdkAccountConfiguration accountConf) {
    return EngineSdkJNI.deleteAccount(EngineSdkAccountConfiguration.getCPtr(accountConf), accountConf);
  }

  public static boolean refreshCurrentAccountRegisterNow() {
    return EngineSdkJNI.refreshCurrentAccountRegisterNow();
  }

  public static void SetForcedRelayPath(String relay_path) {
    EngineSdkJNI.SetForcedRelayPath(relay_path);
  }

  public static boolean answerIncomingCall(EngineSdkCallConfiguration callConf) {
    return EngineSdkJNI.answerIncomingCall(EngineSdkCallConfiguration.getCPtr(callConf), callConf);
  }

  public static boolean endCall(long p_callLocalToken, String callDeclinedReason) {
    return EngineSdkJNI.endCall(p_callLocalToken, callDeclinedReason);
  }

  public static boolean setOrUpdateEngineCallback(EngineSdkEngineCallback engineCallback) {
    return EngineSdkJNI.setOrUpdateEngineCallback(EngineSdkEngineCallback.getCPtr(engineCallback), engineCallback);
  }

  public static boolean setEconomicTrafficMode(boolean isEconomic) {
    return EngineSdkJNI.setEconomicTrafficMode(isEconomic);
  }

  public static int setAudioControl(int mode, EngineSdkEngineAudioControlParameter reserveParam) {
    return EngineSdkJNI.setAudioControl(mode, EngineSdkEngineAudioControlParameter.getCPtr(reserveParam), reserveParam);
  }

  public static int setAudioOutputMode(EngineSdkAudioOutputMode audioOutputMode) {
    return EngineSdkJNI.setAudioOutputMode(audioOutputMode.swigValue());
  }

  public static int setAndroidFilePath(String path) {
    return EngineSdkJNI.setAndroidFilePath(path);
  }

  public static int setAudioProcessingControl(int mode) {
    return EngineSdkJNI.setAudioProcessingControl(mode);
  }

  public static EngineSdkCallInformation startCall(EngineSdkCallConfiguration callConf) {
    return new EngineSdkCallInformation(EngineSdkJNI.startCall(EngineSdkCallConfiguration.getCPtr(callConf), callConf), true);
  }

}
