/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.kinstalk.voip.sdk;

public class EngineSdkAudioChannelConfiguration {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected EngineSdkAudioChannelConfiguration(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(EngineSdkAudioChannelConfiguration obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        EngineSdkJNI.delete_EngineSdkAudioChannelConfiguration(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setSampleRate(int value) {
    EngineSdkJNI.EngineSdkAudioChannelConfiguration_sampleRate_set(swigCPtr, this, value);
  }

  public int getSampleRate() {
    return EngineSdkJNI.EngineSdkAudioChannelConfiguration_sampleRate_get(swigCPtr, this);
  }

  public void setBitLength(int value) {
    EngineSdkJNI.EngineSdkAudioChannelConfiguration_bitLength_set(swigCPtr, this, value);
  }

  public int getBitLength() {
    return EngineSdkJNI.EngineSdkAudioChannelConfiguration_bitLength_get(swigCPtr, this);
  }

  public EngineSdkAudioChannelConfiguration() {
    this(EngineSdkJNI.new_EngineSdkAudioChannelConfiguration(), true);
  }

}
