/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.kinstalk.voip.sdk;

public enum EngineSdkOperatingSystemType {
  ES_OS_TYPE_UNKNOWN,
  ES_OS_TYPE_WIN7,
  ES_OS_TYPE_WIN8,
  ES_OS_TYPE_ANDROID2,
  ES_OS_TYPE_ANDROID3,
  ES_OS_TYPE_ANDROID4,
  ES_OS_TYPE_IOS5,
  ES_OS_TYPE_IOS6,
  ES_OS_TYPE_IOS7;

  public final int swigValue() {
    return swigValue;
  }

  public static EngineSdkOperatingSystemType swigToEnum(int swigValue) {
    EngineSdkOperatingSystemType[] swigValues = EngineSdkOperatingSystemType.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (EngineSdkOperatingSystemType swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + EngineSdkOperatingSystemType.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private EngineSdkOperatingSystemType() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private EngineSdkOperatingSystemType(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private EngineSdkOperatingSystemType(EngineSdkOperatingSystemType swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

