/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.kinstalk.voip.sdk;

public class EngineSdkVideoBiInfo {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected EngineSdkVideoBiInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(EngineSdkVideoBiInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        EngineSdkJNI.delete_EngineSdkVideoBiInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public EngineSdkVideoBiInfo() {
    this(EngineSdkJNI.new_EngineSdkVideoBiInfo(), true);
  }

  public void setFpsCapture(String value) {
    EngineSdkJNI.EngineSdkVideoBiInfo_fpsCapture_set(swigCPtr, this, value);
  }

  public String getFpsCapture() {
    return EngineSdkJNI.EngineSdkVideoBiInfo_fpsCapture_get(swigCPtr, this);
  }

  public void setFpsStrategy(String value) {
    EngineSdkJNI.EngineSdkVideoBiInfo_fpsStrategy_set(swigCPtr, this, value);
  }

  public String getFpsStrategy() {
    return EngineSdkJNI.EngineSdkVideoBiInfo_fpsStrategy_get(swigCPtr, this);
  }

  public void setFpsEncode(String value) {
    EngineSdkJNI.EngineSdkVideoBiInfo_fpsEncode_set(swigCPtr, this, value);
  }

  public String getFpsEncode() {
    return EngineSdkJNI.EngineSdkVideoBiInfo_fpsEncode_get(swigCPtr, this);
  }

  public void setFpsDecode(String value) {
    EngineSdkJNI.EngineSdkVideoBiInfo_fpsDecode_set(swigCPtr, this, value);
  }

  public String getFpsDecode() {
    return EngineSdkJNI.EngineSdkVideoBiInfo_fpsDecode_get(swigCPtr, this);
  }

  public void setFpsRender(String value) {
    EngineSdkJNI.EngineSdkVideoBiInfo_fpsRender_set(swigCPtr, this, value);
  }

  public String getFpsRender() {
    return EngineSdkJNI.EngineSdkVideoBiInfo_fpsRender_get(swigCPtr, this);
  }

  public void setBpsStrategy(String value) {
    EngineSdkJNI.EngineSdkVideoBiInfo_bpsStrategy_set(swigCPtr, this, value);
  }

  public String getBpsStrategy() {
    return EngineSdkJNI.EngineSdkVideoBiInfo_bpsStrategy_get(swigCPtr, this);
  }

  public void setBpsEncode(String value) {
    EngineSdkJNI.EngineSdkVideoBiInfo_bpsEncode_set(swigCPtr, this, value);
  }

  public String getBpsEncode() {
    return EngineSdkJNI.EngineSdkVideoBiInfo_bpsEncode_get(swigCPtr, this);
  }

  public void setBpsSend(String value) {
    EngineSdkJNI.EngineSdkVideoBiInfo_bpsSend_set(swigCPtr, this, value);
  }

  public String getBpsSend() {
    return EngineSdkJNI.EngineSdkVideoBiInfo_bpsSend_get(swigCPtr, this);
  }

  public void setBpsReceive(String value) {
    EngineSdkJNI.EngineSdkVideoBiInfo_bpsReceive_set(swigCPtr, this, value);
  }

  public String getBpsReceive() {
    return EngineSdkJNI.EngineSdkVideoBiInfo_bpsReceive_get(swigCPtr, this);
  }

  public void setBpsDecode(String value) {
    EngineSdkJNI.EngineSdkVideoBiInfo_bpsDecode_set(swigCPtr, this, value);
  }

  public String getBpsDecode() {
    return EngineSdkJNI.EngineSdkVideoBiInfo_bpsDecode_get(swigCPtr, this);
  }

  public void setLossRateSend(String value) {
    EngineSdkJNI.EngineSdkVideoBiInfo_lossRateSend_set(swigCPtr, this, value);
  }

  public String getLossRateSend() {
    return EngineSdkJNI.EngineSdkVideoBiInfo_lossRateSend_get(swigCPtr, this);
  }

  public void setLossRateReceive(String value) {
    EngineSdkJNI.EngineSdkVideoBiInfo_lossRateReceive_set(swigCPtr, this, value);
  }

  public String getLossRateReceive() {
    return EngineSdkJNI.EngineSdkVideoBiInfo_lossRateReceive_get(swigCPtr, this);
  }

  public void setRtt(String value) {
    EngineSdkJNI.EngineSdkVideoBiInfo_rtt_set(swigCPtr, this, value);
  }

  public String getRtt() {
    return EngineSdkJNI.EngineSdkVideoBiInfo_rtt_get(swigCPtr, this);
  }

  public void setJitterSend(String value) {
    EngineSdkJNI.EngineSdkVideoBiInfo_jitterSend_set(swigCPtr, this, value);
  }

  public String getJitterSend() {
    return EngineSdkJNI.EngineSdkVideoBiInfo_jitterSend_get(swigCPtr, this);
  }

  public void setJitterReceive(String value) {
    EngineSdkJNI.EngineSdkVideoBiInfo_jitterReceive_set(swigCPtr, this, value);
  }

  public String getJitterReceive() {
    return EngineSdkJNI.EngineSdkVideoBiInfo_jitterReceive_get(swigCPtr, this);
  }

  public void setStrategyTrend(String value) {
    EngineSdkJNI.EngineSdkVideoBiInfo_strategyTrend_set(swigCPtr, this, value);
  }

  public String getStrategyTrend() {
    return EngineSdkJNI.EngineSdkVideoBiInfo_strategyTrend_get(swigCPtr, this);
  }

  public void setStrategyDetect(String value) {
    EngineSdkJNI.EngineSdkVideoBiInfo_strategyDetect_set(swigCPtr, this, value);
  }

  public String getStrategyDetect() {
    return EngineSdkJNI.EngineSdkVideoBiInfo_strategyDetect_get(swigCPtr, this);
  }

  public void setWidthCapture(String value) {
    EngineSdkJNI.EngineSdkVideoBiInfo_widthCapture_set(swigCPtr, this, value);
  }

  public String getWidthCapture() {
    return EngineSdkJNI.EngineSdkVideoBiInfo_widthCapture_get(swigCPtr, this);
  }

  public void setWidthStrategy(String value) {
    EngineSdkJNI.EngineSdkVideoBiInfo_widthStrategy_set(swigCPtr, this, value);
  }

  public String getWidthStrategy() {
    return EngineSdkJNI.EngineSdkVideoBiInfo_widthStrategy_get(swigCPtr, this);
  }

  public void setWidthEncode(String value) {
    EngineSdkJNI.EngineSdkVideoBiInfo_widthEncode_set(swigCPtr, this, value);
  }

  public String getWidthEncode() {
    return EngineSdkJNI.EngineSdkVideoBiInfo_widthEncode_get(swigCPtr, this);
  }

  public void setWidthDecode(String value) {
    EngineSdkJNI.EngineSdkVideoBiInfo_widthDecode_set(swigCPtr, this, value);
  }

  public String getWidthDecode() {
    return EngineSdkJNI.EngineSdkVideoBiInfo_widthDecode_get(swigCPtr, this);
  }

  public void setWidthRender(String value) {
    EngineSdkJNI.EngineSdkVideoBiInfo_widthRender_set(swigCPtr, this, value);
  }

  public String getWidthRender() {
    return EngineSdkJNI.EngineSdkVideoBiInfo_widthRender_get(swigCPtr, this);
  }

  public void setHeightCapture(String value) {
    EngineSdkJNI.EngineSdkVideoBiInfo_heightCapture_set(swigCPtr, this, value);
  }

  public String getHeightCapture() {
    return EngineSdkJNI.EngineSdkVideoBiInfo_heightCapture_get(swigCPtr, this);
  }

  public void setHeightStrategy(String value) {
    EngineSdkJNI.EngineSdkVideoBiInfo_heightStrategy_set(swigCPtr, this, value);
  }

  public String getHeightStrategy() {
    return EngineSdkJNI.EngineSdkVideoBiInfo_heightStrategy_get(swigCPtr, this);
  }

  public void setHeightEncode(String value) {
    EngineSdkJNI.EngineSdkVideoBiInfo_heightEncode_set(swigCPtr, this, value);
  }

  public String getHeightEncode() {
    return EngineSdkJNI.EngineSdkVideoBiInfo_heightEncode_get(swigCPtr, this);
  }

  public void setHeightDecode(String value) {
    EngineSdkJNI.EngineSdkVideoBiInfo_heightDecode_set(swigCPtr, this, value);
  }

  public String getHeightDecode() {
    return EngineSdkJNI.EngineSdkVideoBiInfo_heightDecode_get(swigCPtr, this);
  }

  public void setHeightRender(String value) {
    EngineSdkJNI.EngineSdkVideoBiInfo_heightRender_set(swigCPtr, this, value);
  }

  public String getHeightRender() {
    return EngineSdkJNI.EngineSdkVideoBiInfo_heightRender_get(swigCPtr, this);
  }

}
