/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.kinstalk.voip.sdk;

public enum EngineSdkMediaChannelSetupMode {
  ES_MEDIA_CHANNEL_DISABLED,
  ES_MEDIA_CHANNEL_PRE_LOADED,
  ES_MEDIA_CHANNEL_SUPPORT_POST_LOADING;

  public final int swigValue() {
    return swigValue;
  }

  public static EngineSdkMediaChannelSetupMode swigToEnum(int swigValue) {
    EngineSdkMediaChannelSetupMode[] swigValues = EngineSdkMediaChannelSetupMode.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (EngineSdkMediaChannelSetupMode swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + EngineSdkMediaChannelSetupMode.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private EngineSdkMediaChannelSetupMode() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private EngineSdkMediaChannelSetupMode(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private EngineSdkMediaChannelSetupMode(EngineSdkMediaChannelSetupMode swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

