/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.kinstalk.voip.sdk;

public class EnginesdkCredentialInformation {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected EnginesdkCredentialInformation(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(EnginesdkCredentialInformation obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        EngineSdkJNI.delete_EnginesdkCredentialInformation(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setRealm(String value) {
    EngineSdkJNI.EnginesdkCredentialInformation_realm_set(swigCPtr, this, value);
  }

  public String getRealm() {
    return EngineSdkJNI.EnginesdkCredentialInformation_realm_get(swigCPtr, this);
  }

  public void setScheme(String value) {
    EngineSdkJNI.EnginesdkCredentialInformation_scheme_set(swigCPtr, this, value);
  }

  public String getScheme() {
    return EngineSdkJNI.EnginesdkCredentialInformation_scheme_get(swigCPtr, this);
  }

  public void setUserName(String value) {
    EngineSdkJNI.EnginesdkCredentialInformation_userName_set(swigCPtr, this, value);
  }

  public String getUserName() {
    return EngineSdkJNI.EnginesdkCredentialInformation_userName_get(swigCPtr, this);
  }

  public void setDataType(int value) {
    EngineSdkJNI.EnginesdkCredentialInformation_dataType_set(swigCPtr, this, value);
  }

  public int getDataType() {
    return EngineSdkJNI.EnginesdkCredentialInformation_dataType_get(swigCPtr, this);
  }

  public void setPassword(String value) {
    EngineSdkJNI.EnginesdkCredentialInformation_password_set(swigCPtr, this, value);
  }

  public String getPassword() {
    return EngineSdkJNI.EnginesdkCredentialInformation_password_get(swigCPtr, this);
  }

  public void setCredentialDigest(String value) {
    EngineSdkJNI.EnginesdkCredentialInformation_credentialDigest_set(swigCPtr, this, value);
  }

  public String getCredentialDigest() {
    return EngineSdkJNI.EnginesdkCredentialInformation_credentialDigest_get(swigCPtr, this);
  }

  public EnginesdkCredentialInformation() {
    this(EngineSdkJNI.new_EnginesdkCredentialInformation(), true);
  }

}
