/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.kinstalk.voip.sdk;

public enum EngineSdkMediaTransportType {
  ES_TP_CHANNEL_TYPE_UNKNOWN,
  ES_TP_CHANNEL_TYPE_P2P_PRIVATE,
  ES_TP_CHANNEL_TYPE_P2P_PUBLIC,
  ES_TP_CHANNEL_TYPE_RELAY;

  public final int swigValue() {
    return swigValue;
  }

  public static EngineSdkMediaTransportType swigToEnum(int swigValue) {
    EngineSdkMediaTransportType[] swigValues = EngineSdkMediaTransportType.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (EngineSdkMediaTransportType swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + EngineSdkMediaTransportType.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private EngineSdkMediaTransportType() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private EngineSdkMediaTransportType(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private EngineSdkMediaTransportType(EngineSdkMediaTransportType swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

