/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.kinstalk.voip.sdk;

public class EngineSdkCpuInformation {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected EngineSdkCpuInformation(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(EngineSdkCpuInformation obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        EngineSdkJNI.delete_EngineSdkCpuInformation(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setCpuCoreCount(int value) {
    EngineSdkJNI.EngineSdkCpuInformation_cpuCoreCount_set(swigCPtr, this, value);
  }

  public int getCpuCoreCount() {
    return EngineSdkJNI.EngineSdkCpuInformation_cpuCoreCount_get(swigCPtr, this);
  }

  public void setCpuFrequencyInMhz(int value) {
    EngineSdkJNI.EngineSdkCpuInformation_cpuFrequencyInMhz_set(swigCPtr, this, value);
  }

  public int getCpuFrequencyInMhz() {
    return EngineSdkJNI.EngineSdkCpuInformation_cpuFrequencyInMhz_get(swigCPtr, this);
  }

  public void setMips(int value) {
    EngineSdkJNI.EngineSdkCpuInformation_mips_set(swigCPtr, this, value);
  }

  public int getMips() {
    return EngineSdkJNI.EngineSdkCpuInformation_mips_get(swigCPtr, this);
  }

  public void setInstruction(EngineSdkCPUInstruction value) {
    EngineSdkJNI.EngineSdkCpuInformation_instruction_set(swigCPtr, this, value.swigValue());
  }

  public EngineSdkCPUInstruction getInstruction() {
    return EngineSdkCPUInstruction.swigToEnum(EngineSdkJNI.EngineSdkCpuInformation_instruction_get(swigCPtr, this));
  }

  public void setManufacturer(EngineSdkCPUManufacturer value) {
    EngineSdkJNI.EngineSdkCpuInformation_manufacturer_set(swigCPtr, this, value.swigValue());
  }

  public EngineSdkCPUManufacturer getManufacturer() {
    return EngineSdkCPUManufacturer.swigToEnum(EngineSdkJNI.EngineSdkCpuInformation_manufacturer_get(swigCPtr, this));
  }

  public EngineSdkCpuInformation() {
    this(EngineSdkJNI.new_EngineSdkCpuInformation(), true);
  }

}
