/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.kinstalk.voip.sdk;

public class EngineSdkEngineCallback {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected EngineSdkEngineCallback(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(EngineSdkEngineCallback obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        EngineSdkJNI.delete_EngineSdkEngineCallback(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    EngineSdkJNI.EngineSdkEngineCallback_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    EngineSdkJNI.EngineSdkEngineCallback_change_ownership(this, swigCPtr, true);
  }

  public void onEngineStateChanged(EngineSdkEngineInformation engineInfo) {
    if (getClass() == EngineSdkEngineCallback.class) EngineSdkJNI.EngineSdkEngineCallback_onEngineStateChanged(swigCPtr, this, EngineSdkEngineInformation.getCPtr(engineInfo), engineInfo); else EngineSdkJNI.EngineSdkEngineCallback_onEngineStateChangedSwigExplicitEngineSdkEngineCallback(swigCPtr, this, EngineSdkEngineInformation.getCPtr(engineInfo), engineInfo);
  }

  public void onAccountStateChanged(EngineSdkAccountInformation accountInfo) {
    if (getClass() == EngineSdkEngineCallback.class) EngineSdkJNI.EngineSdkEngineCallback_onAccountStateChanged(swigCPtr, this, EngineSdkAccountInformation.getCPtr(accountInfo), accountInfo); else EngineSdkJNI.EngineSdkEngineCallback_onAccountStateChangedSwigExplicitEngineSdkEngineCallback(swigCPtr, this, EngineSdkAccountInformation.getCPtr(accountInfo), accountInfo);
  }

  public void onCallStateChanged(EngineSdkCallInformation callInfo) {
    if (getClass() == EngineSdkEngineCallback.class) EngineSdkJNI.EngineSdkEngineCallback_onCallStateChanged(swigCPtr, this, EngineSdkCallInformation.getCPtr(callInfo), callInfo); else EngineSdkJNI.EngineSdkEngineCallback_onCallStateChangedSwigExplicitEngineSdkEngineCallback(swigCPtr, this, EngineSdkCallInformation.getCPtr(callInfo), callInfo);
  }

  public EngineSdkEngineCallback() {
    this(EngineSdkJNI.new_EngineSdkEngineCallback(), true);
    EngineSdkJNI.EngineSdkEngineCallback_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

}
