/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.kinstalk.voip.sdk;

public enum EngineSdkAudioOutputMode {
  ES_AUDIO_OUTPUT_MODE_LOUD_SPEAKER,
  ES_AUDIO_OUTPUT_MODE_SMALL_SPEAKER,
  ES_AUDIO_OUTPUT_MODE_EARSET;

  public final int swigValue() {
    return swigValue;
  }

  public static EngineSdkAudioOutputMode swigToEnum(int swigValue) {
    EngineSdkAudioOutputMode[] swigValues = EngineSdkAudioOutputMode.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (EngineSdkAudioOutputMode swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + EngineSdkAudioOutputMode.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private EngineSdkAudioOutputMode() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private EngineSdkAudioOutputMode(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private EngineSdkAudioOutputMode(EngineSdkAudioOutputMode swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

