/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.kinstalk.voip.sdk;

public enum EngineSdkUacAutoControlUasProcessState {
  ES_UAC_REQ_AUTOCONTROL_UAS_INACTIVE,
  ES_UAC_REQ_AUTOCONTROL_UAS_START,
  ES_UAC_REQ_AUTOCONTROL_UAS_SUCCESS,
  ES_UAC_REQ_AUTOCONTROL_UAS_FAILED;

  public final int swigValue() {
    return swigValue;
  }

  public static EngineSdkUacAutoControlUasProcessState swigToEnum(int swigValue) {
    EngineSdkUacAutoControlUasProcessState[] swigValues = EngineSdkUacAutoControlUasProcessState.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (EngineSdkUacAutoControlUasProcessState swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + EngineSdkUacAutoControlUasProcessState.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private EngineSdkUacAutoControlUasProcessState() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private EngineSdkUacAutoControlUasProcessState(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private EngineSdkUacAutoControlUasProcessState(EngineSdkUacAutoControlUasProcessState swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

