/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.kinstalk.voip.sdk;

public class EngineSdkCallConfiguration {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected EngineSdkCallConfiguration(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(EngineSdkCallConfiguration obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        EngineSdkJNI.delete_EngineSdkCallConfiguration(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    EngineSdkJNI.EngineSdkCallConfiguration_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    EngineSdkJNI.EngineSdkCallConfiguration_change_ownership(this, swigCPtr, true);
  }

  public EngineSdkCallConfiguration() {
    this(EngineSdkJNI.new_EngineSdkCallConfiguration(), true);
    EngineSdkJNI.EngineSdkCallConfiguration_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public void setLocalDisplayName(String value) {
    EngineSdkJNI.EngineSdkCallConfiguration_localDisplayName_set(swigCPtr, this, value);
  }

  public String getLocalDisplayName() {
    return EngineSdkJNI.EngineSdkCallConfiguration_localDisplayName_get(swigCPtr, this);
  }

  public void setRemoteDisplayName(String value) {
    EngineSdkJNI.EngineSdkCallConfiguration_remoteDisplayName_set(swigCPtr, this, value);
  }

  public String getRemoteDisplayName() {
    return EngineSdkJNI.EngineSdkCallConfiguration_remoteDisplayName_get(swigCPtr, this);
  }

  public void setLocalAccountId(String value) {
    EngineSdkJNI.EngineSdkCallConfiguration_localAccountId_set(swigCPtr, this, value);
  }

  public String getLocalAccountId() {
    return EngineSdkJNI.EngineSdkCallConfiguration_localAccountId_get(swigCPtr, this);
  }

  public void setRemoteAccountId(String value) {
    EngineSdkJNI.EngineSdkCallConfiguration_remoteAccountId_set(swigCPtr, this, value);
  }

  public String getRemoteAccountId() {
    return EngineSdkJNI.EngineSdkCallConfiguration_remoteAccountId_get(swigCPtr, this);
  }

  public void setAudioChannelConfiguration(EngineSdkAudioChannelConfiguration value) {
    EngineSdkJNI.EngineSdkCallConfiguration_audioChannelConfiguration_set(swigCPtr, this, EngineSdkAudioChannelConfiguration.getCPtr(value), value);
  }

  public EngineSdkAudioChannelConfiguration getAudioChannelConfiguration() {
    long cPtr = EngineSdkJNI.EngineSdkCallConfiguration_audioChannelConfiguration_get(swigCPtr, this);
    return (cPtr == 0) ? null : new EngineSdkAudioChannelConfiguration(cPtr, false);
  }

  public void setMainVideoChannelConfiguration(EngineSdkVideoChannelConfiguration value) {
    EngineSdkJNI.EngineSdkCallConfiguration_mainVideoChannelConfiguration_set(swigCPtr, this, EngineSdkVideoChannelConfiguration.getCPtr(value), value);
  }

  public EngineSdkVideoChannelConfiguration getMainVideoChannelConfiguration() {
    long cPtr = EngineSdkJNI.EngineSdkCallConfiguration_mainVideoChannelConfiguration_get(swigCPtr, this);
    return (cPtr == 0) ? null : new EngineSdkVideoChannelConfiguration(cPtr, false);
  }

  public void setSecondVideoChannelConfiguration(EngineSdkVideoChannelConfiguration value) {
    EngineSdkJNI.EngineSdkCallConfiguration_secondVideoChannelConfiguration_set(swigCPtr, this, EngineSdkVideoChannelConfiguration.getCPtr(value), value);
  }

  public EngineSdkVideoChannelConfiguration getSecondVideoChannelConfiguration() {
    long cPtr = EngineSdkJNI.EngineSdkCallConfiguration_secondVideoChannelConfiguration_get(swigCPtr, this);
    return (cPtr == 0) ? null : new EngineSdkVideoChannelConfiguration(cPtr, false);
  }

  public void setDataChannelConfiguration(EngineSdkDataChannelConfiguration value) {
    EngineSdkJNI.EngineSdkCallConfiguration_dataChannelConfiguration_set(swigCPtr, this, EngineSdkDataChannelConfiguration.getCPtr(value), value);
  }

  public EngineSdkDataChannelConfiguration getDataChannelConfiguration() {
    long cPtr = EngineSdkJNI.EngineSdkCallConfiguration_dataChannelConfiguration_get(swigCPtr, this);
    return (cPtr == 0) ? null : new EngineSdkDataChannelConfiguration(cPtr, false);
  }

  public void setAudioChannelEnabled(boolean value) {
    EngineSdkJNI.EngineSdkCallConfiguration_audioChannelEnabled_set(swigCPtr, this, value);
  }

  public boolean getAudioChannelEnabled() {
    return EngineSdkJNI.EngineSdkCallConfiguration_audioChannelEnabled_get(swigCPtr, this);
  }

  public void setMainVideoChannelEnabled(boolean value) {
    EngineSdkJNI.EngineSdkCallConfiguration_mainVideoChannelEnabled_set(swigCPtr, this, value);
  }

  public boolean getMainVideoChannelEnabled() {
    return EngineSdkJNI.EngineSdkCallConfiguration_mainVideoChannelEnabled_get(swigCPtr, this);
  }

  public void setSecondVideoChannelEnabled(boolean value) {
    EngineSdkJNI.EngineSdkCallConfiguration_secondVideoChannelEnabled_set(swigCPtr, this, value);
  }

  public boolean getSecondVideoChannelEnabled() {
    return EngineSdkJNI.EngineSdkCallConfiguration_secondVideoChannelEnabled_get(swigCPtr, this);
  }

  public void setDataVideoChannelEnabled(boolean value) {
    EngineSdkJNI.EngineSdkCallConfiguration_dataVideoChannelEnabled_set(swigCPtr, this, value);
  }

  public boolean getDataVideoChannelEnabled() {
    return EngineSdkJNI.EngineSdkCallConfiguration_dataVideoChannelEnabled_get(swigCPtr, this);
  }

  public void setCall_id(int value) {
    EngineSdkJNI.EngineSdkCallConfiguration_call_id_set(swigCPtr, this, value);
  }

  public int getCall_id() {
    return EngineSdkJNI.EngineSdkCallConfiguration_call_id_get(swigCPtr, this);
  }

  public void setCallLocalToken(long value) {
    EngineSdkJNI.EngineSdkCallConfiguration_callLocalToken_set(swigCPtr, this, value);
  }

  public long getCallLocalToken() {
    return EngineSdkJNI.EngineSdkCallConfiguration_callLocalToken_get(swigCPtr, this);
  }

  public void setLocalAccountInternalId(int value) {
    EngineSdkJNI.EngineSdkCallConfiguration_localAccountInternalId_set(swigCPtr, this, value);
  }

  public int getLocalAccountInternalId() {
    return EngineSdkJNI.EngineSdkCallConfiguration_localAccountInternalId_get(swigCPtr, this);
  }

  public void setUacRequestAutoControlUasState(EngineSdkUacAutoControlUasProcessState value) {
    EngineSdkJNI.EngineSdkCallConfiguration_uacRequestAutoControlUasState_set(swigCPtr, this, value.swigValue());
  }

  public EngineSdkUacAutoControlUasProcessState getUacRequestAutoControlUasState() {
    return EngineSdkUacAutoControlUasProcessState.swigToEnum(EngineSdkJNI.EngineSdkCallConfiguration_uacRequestAutoControlUasState_get(swigCPtr, this));
  }

  public void setCallDirection(EngineSdkSessionDirection value) {
    EngineSdkJNI.EngineSdkCallConfiguration_callDirection_set(swigCPtr, this, value.swigValue());
  }

  public EngineSdkSessionDirection getCallDirection() {
    return EngineSdkSessionDirection.swigToEnum(EngineSdkJNI.EngineSdkCallConfiguration_callDirection_get(swigCPtr, this));
  }

  public void setCallCallback(EngineSdkCallCallback value) {
    EngineSdkJNI.EngineSdkCallConfiguration_callCallback_set(swigCPtr, this, EngineSdkCallCallback.getCPtr(value), value);
  }

  public EngineSdkCallCallback getCallCallback() {
    long cPtr = EngineSdkJNI.EngineSdkCallConfiguration_callCallback_get(swigCPtr, this);
    return (cPtr == 0) ? null : new EngineSdkCallCallback(cPtr, false);
  }

  public void setMediaAudioCallback(EngineSdkMediaAudioCallback value) {
    EngineSdkJNI.EngineSdkCallConfiguration_mediaAudioCallback_set(swigCPtr, this, EngineSdkMediaAudioCallback.getCPtr(value), value);
  }

  public EngineSdkMediaAudioCallback getMediaAudioCallback() {
    long cPtr = EngineSdkJNI.EngineSdkCallConfiguration_mediaAudioCallback_get(swigCPtr, this);
    return (cPtr == 0) ? null : new EngineSdkMediaAudioCallback(cPtr, false);
  }

  public void setMainVideoCallback(EngineSdkMediaMainVideoCallback value) {
    EngineSdkJNI.EngineSdkCallConfiguration_mainVideoCallback_set(swigCPtr, this, EngineSdkMediaMainVideoCallback.getCPtr(value), value);
  }

  public EngineSdkMediaMainVideoCallback getMainVideoCallback() {
    long cPtr = EngineSdkJNI.EngineSdkCallConfiguration_mainVideoCallback_get(swigCPtr, this);
    return (cPtr == 0) ? null : new EngineSdkMediaMainVideoCallback(cPtr, false);
  }

  public void setSecondVideoCallback(EngineSdkMediaSecondVideoCallback value) {
    EngineSdkJNI.EngineSdkCallConfiguration_secondVideoCallback_set(swigCPtr, this, EngineSdkMediaSecondVideoCallback.getCPtr(value), value);
  }

  public EngineSdkMediaSecondVideoCallback getSecondVideoCallback() {
    long cPtr = EngineSdkJNI.EngineSdkCallConfiguration_secondVideoCallback_get(swigCPtr, this);
    return (cPtr == 0) ? null : new EngineSdkMediaSecondVideoCallback(cPtr, false);
  }

  public void setDataCallback(EngineSdkMediaDataCallback value) {
    EngineSdkJNI.EngineSdkCallConfiguration_dataCallback_set(swigCPtr, this, EngineSdkMediaDataCallback.getCPtr(value), value);
  }

  public EngineSdkMediaDataCallback getDataCallback() {
    long cPtr = EngineSdkJNI.EngineSdkCallConfiguration_dataCallback_get(swigCPtr, this);
    return (cPtr == 0) ? null : new EngineSdkMediaDataCallback(cPtr, false);
  }

  public void setBiExceptionCallback(EngineSdkBiExceptionCallback value) {
    EngineSdkJNI.EngineSdkCallConfiguration_biExceptionCallback_set(swigCPtr, this, EngineSdkBiExceptionCallback.getCPtr(value), value);
  }

  public EngineSdkBiExceptionCallback getBiExceptionCallback() {
    long cPtr = EngineSdkJNI.EngineSdkCallConfiguration_biExceptionCallback_get(swigCPtr, this);
    return (cPtr == 0) ? null : new EngineSdkBiExceptionCallback(cPtr, false);
  }

  public void setIsRandomCall(boolean value) {
    EngineSdkJNI.EngineSdkCallConfiguration_isRandomCall_set(swigCPtr, this, value);
  }

  public boolean getIsRandomCall() {
    return EngineSdkJNI.EngineSdkCallConfiguration_isRandomCall_get(swigCPtr, this);
  }

  public EngineSdkCallConfiguration clone() {
    long cPtr = EngineSdkJNI.EngineSdkCallConfiguration_clone(swigCPtr, this);
    return (cPtr == 0) ? null : new EngineSdkCallConfiguration(cPtr, false);
  }

}
