/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.kinstalk.voip.sdk;

public enum EngineSdkCallEndReason {
  ES_CALL_NOT_END,
  ES_CALL_NORMAL_END,
  ES_CALl_END_UNKNOWN_REASON,
  ES_CALl_END_MAX_CALL_COUNT_REACHED,
  ES_CALl_END_NO_ACCOUNT_AVAILABLE,
  ES_CALl_END_NO_ENGINE_AVAILABLE,
  ES_CALl_END_WRONG_PARAMETER,
  ES_CALL_END_CONNECTION_INTERRUPTED_PLS_TRY_LATER,
  ES_CALL_END_CALLED_USER_NO_RESPONSE_PLS_TRY_LATER,
  ES_CALL_END_SERVICE_UNAVAILABLE_PLS_CHECK_NETWORK_CONFIGURATION,
  ES_CALL_END_SERVICE_UNAVAILABLE_PLS_TRY_LATER,
  ES_CALL_END_CALLED_USER_NOT_ONLINE_PLS_TRY_LATER,
  ES_CALL_END_CALLED_USER_NOT_ANSWER_PLS_TRY_LATER,
  ES_CALL_END_CALLED_USER_UNREACHABLE_PLS_TRY_LATER,
  ES_CALL_END_CANCELLED,
  ES_CALL_END_CALLEE_IN_SESSION_PLS_TRY_LATER,
  ES_CALL_END_CALLEE_BUSY_PLS_TRY_LATER,
  ES_CALL_END_FORBIDDED_BY_REMOTE,
  ES_CALL_END_LOGON_TIMEOUT,
  ES_CALL_END_CALLEE_IS_NOT_YOUR_FRRIEND,
  ES_CALL_END_CALLEE_IN_BL_OF_CALLER,
  ES_CALL_END_CALLER_IN_BL_OF_CALLEE;

  public final int swigValue() {
    return swigValue;
  }

  public static EngineSdkCallEndReason swigToEnum(int swigValue) {
    EngineSdkCallEndReason[] swigValues = EngineSdkCallEndReason.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (EngineSdkCallEndReason swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + EngineSdkCallEndReason.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private EngineSdkCallEndReason() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private EngineSdkCallEndReason(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private EngineSdkCallEndReason(EngineSdkCallEndReason swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

